import fs from 'node:fs'
import path from 'node:path'
import crypto from 'node:crypto'

const root = process.cwd(); const pilotDir = path.join(root, 'clinical-expansion-v2/progress/source-engine-pilot'); const read = (file) => JSON.parse(fs.readFileSync(file, 'utf8')); const write = (file, value) => fs.writeFileSync(file, `${JSON.stringify(value, null, 2)}\n`); const sha = (value) => crypto.createHash('sha256').update(JSON.stringify(value)).digest('hex')
const details = read(path.join(pilotDir, 'PILOT_DETAILS.json')); const activation = read(path.join(pilotDir, 'DEEP_PILOT_ACTIVATION_RESULTS.json')); const activated = details.filter((detail) => detail.usable)
const finalDir = path.join(root, 'public/data-beta/final-catalogue'); const interactiveDir = path.join(root, 'public/data-beta/interactive-workflows')
const finalCatalog = read(path.join(finalDir, 'catalog.json')); const inactive = read(path.join(finalDir, 'inactive-inventory.json')); const finalMeta = read(path.join(finalDir, 'metadata.json')); const finalManifest = read(path.join(finalDir, 'manifest.json')); const interactiveCatalog = read(path.join(interactiveDir, 'catalog.json')); const interactiveManifest = read(path.join(interactiveDir, 'manifest.json'))
const activeIds = new Set(finalCatalog.workflows.map((row) => row.workflow_id)); const activatedIds = new Set(activated.map((detail) => detail.workflow_id)); if (activated.some((detail) => activeIds.has(detail.workflow_id))) throw new Error('Pilot workflow already active')
const toFinal = (detail) => ({ workflow_id: detail.workflow_id, title: detail.title, specialty: detail.specialty, archetype: detail.archetype, final_status: detail.final_status, usable: true, evidence_pack_ids: detail.evidence_pack_ids, sections: [...new Set(detail.fields.map((field) => field.section))], metadata_sections: ['scope'], internal_evidence_record_count: detail.evidence_records.length, provenance_only_record_count: 0, user_facing_item_count: detail.user_facing_items.length, user_facing_items: detail.user_facing_items.map(({ evidence: _evidence, ...item }) => item), evidence_records: detail.evidence_records.map((record, index) => ({ ...record, item_id: `${detail.workflow_id}--evidence--${record.evidence_statement_id}`, stable_item_id: `${detail.workflow_id}--evidence--${record.evidence_statement_id}`, record_type: 'evidence', display_order: index + 1 })), exact_duplicates_removed: 0, near_duplicates_consolidated: 0, repeated_source_paraphrases: 0, concept_groups_consolidated: 0, hidden_audit_records: 0, additions_count: detail.user_facing_items.length, rewrites_count: 0, removals_count: 0, limitations: ['Pilot schema is documentation-only and does not provide diagnosis, prescribing or autonomous decision support.'], missing_required_sections: [] })
const newFinal = activated.map(toFinal); const newInteractive = activated.map((detail) => ({ workflow_id: detail.workflow_id, title: detail.title, specialty: detail.specialty, archetype: detail.archetype, population: detail.population ? [detail.population] : [], settings: detail.setting ? [detail.setting] : [], final_status: detail.final_status, evidence_pack_ids: detail.evidence_pack_ids, evidence_statement_count: detail.evidence_records.length, fields: detail.fields, evidence: detail.evidence_records.map((record) => ({ evidence_statement_id: record.evidence_statement_id, source_id: record.source_id, official_source_url: record.official_source_url, locator: record.exact_locator })) }))
for (const detail of newFinal) write(path.join(finalDir, 'workflows', `${detail.workflow_id}.json`), detail)
for (const detail of newInteractive) write(path.join(interactiveDir, 'workflows', `${detail.workflow_id}.json`), detail)
const finalSummaries = [...finalCatalog.workflows, ...newFinal.map((detail) => ({ workflow_id: detail.workflow_id, title: detail.title, specialty: detail.specialty, archetype: detail.archetype, final_status: detail.final_status, usable: true, evidence_pack_ids: detail.evidence_pack_ids, sections: detail.sections, metadata_sections: detail.metadata_sections, internal_evidence_record_count: detail.internal_evidence_record_count, provenance_only_record_count: 0, user_facing_item_count: detail.user_facing_item_count }))].sort((a, b) => a.workflow_id.localeCompare(b.workflow_id))
const inactiveWorkflows = inactive.workflows.filter((row) => !activatedIds.has(row.workflow_id)); const clinicianItemsAdded = newFinal.reduce((sum, row) => sum + row.user_facing_item_count, 0); const evidenceAdded = newFinal.reduce((sum, row) => sum + row.internal_evidence_record_count, 0)
write(path.join(finalDir, 'catalog.json'), { ...finalCatalog, usable_workflow_count: finalSummaries.length, inactive_workflow_count: inactiveWorkflows.length, workflows: finalSummaries }); write(path.join(finalDir, 'inactive-inventory.json'), { ...inactive, workflow_count: inactiveWorkflows.length, workflows: inactiveWorkflows })
write(path.join(finalDir, 'metadata.json'), { ...finalMeta, usable_workflow_count: finalSummaries.length, inactive_workflow_count: inactiveWorkflows.length, user_facing_item_count: finalMeta.user_facing_item_count + clinicianItemsAdded, internal_evidence_record_count: finalMeta.internal_evidence_record_count + evidenceAdded })
write(path.join(finalDir, 'manifest.json'), { ...finalManifest, source_commit: 'beta-source-engine-repair-and-deep-pilot-v1', counts: { ...finalManifest.counts, active_workflows: finalSummaries.length, inactive_workflows: inactiveWorkflows.length, clinician_facing_items: finalManifest.counts.clinician_facing_items + clinicianItemsAdded, internal_evidence_records: finalManifest.counts.internal_evidence_records + evidenceAdded }, fingerprints: { ...finalManifest.fingerprints, app_manifest: sha({ source: 'wave10-deep-pilot', active: finalSummaries.map((row) => row.workflow_id), inactive: inactiveWorkflows.map((row) => row.workflow_id) }) } })
const interactiveDetails = [...interactiveCatalog.workflows.map((summary) => read(path.join(interactiveDir, 'workflows', `${summary.workflow_id}.json`))), ...newInteractive].sort((a, b) => a.workflow_id.localeCompare(b.workflow_id)); const interactiveSummaries = interactiveDetails.map((detail) => ({ workflow_id: detail.workflow_id, title: detail.title, specialty: detail.specialty, archetype: detail.archetype, final_status: detail.final_status, fields: detail.fields.length, evidence_records: detail.evidence.length })); const fieldCount = interactiveDetails.reduce((sum, detail) => sum + detail.fields.length, 0); const evidenceCount = interactiveDetails.reduce((sum, detail) => sum + detail.evidence.length, 0)
write(path.join(interactiveDir, 'catalog.json'), { schema_version: '1.0.0', workflows: interactiveSummaries }); write(path.join(interactiveDir, 'manifest.json'), { ...interactiveManifest, generated_from: 'source-engine-deep-pilot', counts: { workflows: interactiveDetails.length, fields: fieldCount, evidence_records_retained: evidenceCount }, workflow_fingerprint: sha(interactiveDetails.map(({ evidence: _evidence, ...detail }) => detail)), interactive_manifest_fingerprint: sha(interactiveDetails) })
const updatedActivation = { ...activation, activated_count: activated.length, reactivated_count: activated.filter((detail) => detail.terminal_outcome.startsWith('reactivated_')).length, remaining_inactive_count: details.length - activated.length, results: details.map((detail) => ({ workflow_id: detail.workflow_id, final_state: detail.terminal_outcome, fields: detail.usable ? detail.fields.length : 0, source_ids: detail.source_ids, fail_closed: !detail.usable })) }; write(path.join(pilotDir, 'DEEP_PILOT_ACTIVATION_RESULTS.json'), updatedActivation)
write(path.join(pilotDir, 'TEST_RESULTS.json'), { schema_version: '1.0.0', status: 'PASS_BASELINE_PENDING_BROWSER', pilot_targets: details.length, activated: activated.length, reactivated: updatedActivation.reactivated_count, remaining_inactive: details.length - activated.length, fields_added: clinicianItemsAdded, selectable_controls_added: activated.reduce((sum, detail) => sum + detail.fields.filter((field) => field.options.length).length, 0), contradiction_groups_added: activated.reduce((sum, detail) => sum + detail.fields.filter((field) => field.contradictory_option_rules.length).length, 0), conditional_rules_added: 0, source_engine_tests: 10, source_registry_before: 242, source_registry_canonical_unchanged: true })
console.log(JSON.stringify({ status: 'PASS', activated: activated.length, remaining_inactive: details.length - activated.length, active_workflows: finalSummaries.length, inactive_workflows: inactiveWorkflows.length, fields: fieldCount, evidence: evidenceCount }, null, 2))
