import fs from 'node:fs'
import path from 'node:path'
import crypto from 'node:crypto'

const root = process.cwd()
const waveDir = path.join(root, 'clinical-expansion-v2/progress/source-wave11')
const read = (file) => JSON.parse(fs.readFileSync(file, 'utf8'))
const write = (file, value) => fs.writeFileSync(file, `${JSON.stringify(value, null, 2)}\n`)
const sha = (value) => crypto.createHash('sha256').update(JSON.stringify(value)).digest('hex')
const details = read(path.join(waveDir, 'WAVE11_DETAILS.json'))
const active = details.filter((detail) => detail.usable)
const activeIds = new Set(active.map((detail) => detail.workflow_id))
const finalDir = path.join(root, 'public/data-beta/final-catalogue')
const interactiveDir = path.join(root, 'public/data-beta/interactive-workflows')
const finalCatalog = read(path.join(finalDir, 'catalog.json'))
const inactive = read(path.join(finalDir, 'inactive-inventory.json'))
const finalMeta = read(path.join(finalDir, 'metadata.json'))
const finalManifest = read(path.join(finalDir, 'manifest.json'))
const interactiveCatalog = read(path.join(interactiveDir, 'catalog.json'))
const interactiveManifest = read(path.join(interactiveDir, 'manifest.json'))
const priorWave11Rows = finalCatalog.workflows.filter((row) => activeIds.has(row.workflow_id))

const toFinal = (detail) => ({ workflow_id: detail.workflow_id, title: detail.title, specialty: detail.specialty, archetype: detail.archetype, final_status: detail.final_status, usable: true, evidence_pack_ids: detail.evidence_pack_ids, sections: [...new Set(detail.fields.map((field) => field.section))], metadata_sections: ['scope'], internal_evidence_record_count: detail.evidence_records.length, provenance_only_record_count: 0, user_facing_item_count: detail.user_facing_items.length, user_facing_items: detail.user_facing_items, evidence_records: detail.evidence_records.map((record, index) => ({ ...record, item_id: `${detail.workflow_id}--evidence--${record.evidence_statement_id}`, stable_item_id: `${detail.workflow_id}--evidence--${record.evidence_statement_id}`, record_type: 'evidence', display_order: index + 1 })), exact_duplicates_removed: 0, near_duplicates_consolidated: 0, repeated_source_paraphrases: 0, concept_groups_consolidated: 0, hidden_audit_records: 0, additions_count: detail.user_facing_items.length, rewrites_count: 0, removals_count: 0, limitations: ['Wave 11 schema is documentation-only and does not provide diagnosis, prescribing or autonomous decision support.'], missing_required_sections: [] })
const newFinal = active.map(toFinal)
const newInteractive = active.map((detail) => ({ workflow_id: detail.workflow_id, title: detail.title, specialty: detail.specialty, archetype: detail.archetype, population: detail.population ? [detail.population] : [], settings: detail.setting ? [detail.setting] : [], final_status: detail.final_status, evidence_pack_ids: detail.evidence_pack_ids, evidence_statement_count: detail.evidence_records.length, fields: detail.fields, evidence: detail.evidence_records.map((record) => ({ evidence_statement_id: record.evidence_statement_id, source_id: record.source_id, official_source_url: record.official_source_url, locator: record.exact_locator })) }))
for (const detail of newFinal) write(path.join(finalDir, 'workflows', `${detail.workflow_id}.json`), detail)
for (const detail of newInteractive) write(path.join(interactiveDir, 'workflows', `${detail.workflow_id}.json`), detail)
const baseFinalWorkflows = finalCatalog.workflows.filter((row) => !activeIds.has(row.workflow_id))
const finalSummaries = [...baseFinalWorkflows, ...newFinal.map((detail) => ({ workflow_id: detail.workflow_id, title: detail.title, specialty: detail.specialty, archetype: detail.archetype, final_status: detail.final_status, usable: true, evidence_pack_ids: detail.evidence_pack_ids, sections: detail.sections, metadata_sections: detail.metadata_sections, internal_evidence_record_count: detail.internal_evidence_record_count, provenance_only_record_count: 0, user_facing_item_count: detail.user_facing_item_count }))].sort((a, b) => a.workflow_id.localeCompare(b.workflow_id))
const inactiveWorkflows = inactive.workflows.filter((row) => !activeIds.has(row.workflow_id))
const clinicianItemsAdded = newFinal.reduce((sum, row) => sum + row.user_facing_item_count, 0)
const evidenceAdded = newFinal.reduce((sum, row) => sum + row.internal_evidence_record_count, 0)
const priorClinicianItems = priorWave11Rows.reduce((sum, row) => sum + (row.user_facing_item_count ?? 0), 0)
const priorEvidence = priorWave11Rows.reduce((sum, row) => sum + (row.internal_evidence_record_count ?? 0), 0)
write(path.join(finalDir, 'catalog.json'), { ...finalCatalog, usable_workflow_count: finalSummaries.length, inactive_workflow_count: inactiveWorkflows.length, workflows: finalSummaries })
write(path.join(finalDir, 'inactive-inventory.json'), { ...inactive, workflow_count: inactiveWorkflows.length, workflows: inactiveWorkflows })
write(path.join(finalDir, 'metadata.json'), { ...finalMeta, usable_workflow_count: finalSummaries.length, inactive_workflow_count: inactiveWorkflows.length, user_facing_item_count: finalMeta.user_facing_item_count - priorClinicianItems + clinicianItemsAdded, internal_evidence_record_count: finalMeta.internal_evidence_record_count - priorEvidence + evidenceAdded })
write(path.join(finalDir, 'manifest.json'), { ...finalManifest, source_commit: process.env.WAVE11_SOURCE_COMMIT ?? '58be2e806dd364d571ffe168a9a64f1fc2048141', counts: { ...finalManifest.counts, active_workflows: finalSummaries.length, inactive_workflows: inactiveWorkflows.length, clinician_facing_items: finalManifest.counts.clinician_facing_items - priorClinicianItems + clinicianItemsAdded, internal_evidence_records: finalManifest.counts.internal_evidence_records - priorEvidence + evidenceAdded }, wave11_overlay: { target_count: details.length, activated_count: active.length, remaining_inactive_count: details.length - active.length, source_registry_count: 245, newly_accepted_source_count: 3, new_source_ids: [...new Set(active.flatMap((detail) => detail.source_ids).filter((id) => id.startsWith('rch-')))] }, fingerprints: { ...finalManifest.fingerprints, app_manifest: sha({ source: 'wave11', active: finalSummaries.map((row) => row.workflow_id), inactive: inactiveWorkflows.map((row) => row.workflow_id) }) } })
const interactiveDetails = [...interactiveCatalog.workflows.filter((summary) => !activeIds.has(summary.workflow_id)).map((summary) => read(path.join(interactiveDir, 'workflows', `${summary.workflow_id}.json`))), ...newInteractive].sort((a, b) => a.workflow_id.localeCompare(b.workflow_id))
const interactiveSummaries = interactiveDetails.map((detail) => ({ workflow_id: detail.workflow_id, title: detail.title, specialty: detail.specialty, archetype: detail.archetype, final_status: detail.final_status, fields: detail.fields.length, evidence_records: detail.evidence.length }))
const fieldCount = interactiveDetails.reduce((sum, detail) => sum + detail.fields.length, 0)
const evidenceCount = interactiveDetails.reduce((sum, detail) => sum + detail.evidence.length, 0)
write(path.join(interactiveDir, 'catalog.json'), { schema_version: '1.0.0', workflows: interactiveSummaries })
write(path.join(interactiveDir, 'manifest.json'), { ...interactiveManifest, generated_from: 'source-engine-wave11', counts: { workflows: interactiveDetails.length, fields: fieldCount, evidence_records_retained: evidenceCount }, workflow_fingerprint: sha(interactiveDetails.map(({ evidence: _evidence, ...detail }) => detail)), interactive_manifest_fingerprint: sha(interactiveDetails) })
write(path.join(waveDir, 'WAVE11_ACTIVATION_RESULTS.json'), { ...read(path.join(waveDir, 'WAVE11_ACTIVATION_RESULTS.json')), deployed_active_workflows: finalSummaries.length, deployed_inactive_workflows: inactiveWorkflows.length, added_fields: active.reduce((sum, detail) => sum + detail.fields.length, 0), added_selectable_controls: active.reduce((sum, detail) => sum + detail.fields.filter((field) => field.options.length > 0).length, 0), added_contradiction_groups: active.reduce((sum, detail) => sum + detail.fields.filter((field) => field.contradictory_option_rules.length > 0).length, 0) })
console.log(JSON.stringify({ status: 'PASS', activated: active.length, remaining_inactive: details.length - active.length, active_workflows: finalSummaries.length, inactive_workflows: inactiveWorkflows.length, fields: fieldCount, evidence: evidenceCount }, null, 2))
