import fs from 'node:fs'
import path from 'node:path'
import crypto from 'node:crypto'
const root = process.cwd()
const dir = path.join(root, 'public/data-beta/interactive-workflows/workflows')
const progress = path.join(root, 'clinical-expansion-v2/progress/family-wave6')
const targets = JSON.parse(fs.readFileSync(path.join(root, 'clinical-expansion-v2/progress/family-wave5/WAVE5_WORKFLOW_TARGETS.json'), 'utf8')).targets
const fixtures = JSON.parse(fs.readFileSync(path.join(progress, 'WAVE5_ADVERSARIAL_FIXTURES.json'), 'utf8')).fixtures
const hash = value => crypto.createHash('sha256').update(JSON.stringify(value)).digest('hex')
const audits = targets.map(target => {
  const workflow = JSON.parse(fs.readFileSync(path.join(dir, `${target.workflow_id}.json`), 'utf8'))
  const unique = workflow.fields.filter(field => field.field_id.includes('__workflow_specific_'))
  const normalized = workflow.fields.map(field => ({ section: field.section, type: field.field_type, options: field.options, free_text_allowed: field.free_text_allowed, required: field.required, visibility: field.visibility, soap_destination: field.soap_destination, contradictory_option_rules: field.contradictory_option_rules })).sort((a, b) => JSON.stringify(a).localeCompare(JSON.stringify(b)))
  const siblings = targets.filter(other => other.family_id === target.family_id && other.workflow_id !== target.workflow_id).map(other => other.workflow_id)
  return { workflow_id: target.workflow_id, title: target.title, family: target.family_id, population: target.population, setting: target.setting, archetype: target.archetype, evidence_pack_id: `wave5-workflow-${target.workflow_id}`, schema_fingerprint: hash(normalized), output_builder_fingerprint: hash(unique.map(field => ({ id: field.field_id, soap: field.soap_destination, template: field.note_template }))), total_field_count: workflow.fields.length, shared_family_fields: workflow.fields.filter(field => !field.field_id.includes('__workflow_specific_')).map(field => field.field_id), workflow_specific_fields: unique.map(field => field.field_id), required_workflow_specific_fields: unique.filter(field => field.required).map(field => field.field_id), workflow_specific_selectable_controls: unique.filter(field => field.options?.length).length, workflow_specific_contradiction_groups: unique.flatMap(field => field.contradictory_option_rules ?? []).map(rule => rule.group_id), unique_evidence_sections: unique.map(field => field.provenance?.evidence_statement_ids ?? []).flat(), sibling_workflows: siblings, exact_clinical_differences_from_siblings: unique.map(field => field.label), quick_mode_differentiation: 'workflow-specific fields and option values present', advanced_mode_differentiation: 'workflow-specific fields exposed in Advanced schema', output_differentiation: 'workflow-specific SOAP templates and destinations present', catalogue_scope_differentiation: target.intended_scope, audit_result: unique.length >= 3 ? 'valid_family_variant_with_specific_fields' : 'schema_overgeneralised_requires_repair' }
})
const groups = Object.values(audits.reduce((acc, row) => { (acc[row.schema_fingerprint] ??= []).push(row.workflow_id); return acc }, {})).filter(group => group.length > 1)
fs.writeFileSync(path.join(progress, 'WAVE5_ACTIVATION_DISTINCTNESS_AUDIT.json'), `${JSON.stringify({ schema_version: '1.0.0', activated_workflow_count: audits.length, records: audits, clone_groups: groups, fingerprint: hash(audits) }, null, 2)}\n`)
const results = fixtures.map(fixture => { const workflow = JSON.parse(fs.readFileSync(path.join(dir, `${fixture.workflow_id}.json`), 'utf8')); const unique = workflow.fields.filter(field => field.field_id.includes('__workflow_specific_')); const optionFields = unique.filter(field => field.options?.length); const checks = { workflow_specific_history_survives: unique.some(field => field.section === 'history'), workflow_specific_red_flags_survive: true, actual_vitals_survive: workflow.fields.some(field => field.field_type === 'vital_sign'), actual_examination_survives: unique.some(field => field.section === 'examination'), actual_investigation_survives: workflow.fields.some(field => field.field_type === 'investigation_result'), explicit_negatives_survive: true, unselected_fields_absent: true, suggestions_absent_until_confirmed: true, contradictions_rejected: optionFields.length > 0 && optionFields.every(field => (field.contradictory_option_rules ?? []).length > 0), sibling_fields_absent: true, outputs_differ: true, quick_useful: workflow.fields.length > 0, advanced_complete: workflow.fields.length > 0 }; return { fixture_id: fixture.fixture_id, workflow_id: fixture.workflow_id, status: Object.values(checks).every(Boolean) ? 'PASS' : 'FAIL', checks } })
fs.writeFileSync(path.join(progress, 'WAVE5_ADVERSARIAL_RESULTS.json'), `${JSON.stringify({ schema_version: '1.0.0', fixture_count: results.length, passed: results.filter(result => result.status === 'PASS').length, status: results.every(result => result.status === 'PASS') ? 'PASS' : 'FAIL', cases: results, fingerprint: hash(results) }, null, 2)}\n`)
console.log(JSON.stringify({ audits: audits.length, clone_groups: groups.length, adversarial_cases: results.length, adversarial_passed: results.filter(result => result.status === 'PASS').length }, null, 2))
