import fs from 'node:fs'
import path from 'node:path'
import crypto from 'node:crypto'
const root = process.cwd(); const dir = path.join(root, 'clinical-expansion-v2/progress/catalogue-wave9')
const read = file => JSON.parse(fs.readFileSync(path.join(root, file), 'utf8')); const write = (file, value) => fs.writeFileSync(path.join(dir, file), `${JSON.stringify(value, null, 2)}\n`); const hash = value => crypto.createHash('sha256').update(JSON.stringify(value)).digest('hex')
const manifest = read('public/data-beta/interactive-workflows/manifest.json'); const catalog = read('public/data-beta/final-catalogue/manifest.json'); const targets = read('clinical-expansion-v2/progress/catalogue-wave9/WAVE9_WORKFLOW_TARGETS.json')
const files = fs.readdirSync(path.join(root, 'public/data-beta/interactive-workflows/workflows')).filter(file => file.endsWith('.json')).map(file => read(`public/data-beta/interactive-workflows/workflows/${file}`));
const outputs = files.filter(row => targets.targets.some(target => target.workflow_id === row.workflow_id)).map(row => ({ workflow_id: row.workflow_id, evidence_pack_ids: row.evidence_pack_ids, field_count: row.fields.length, soap_destinations: [...new Set(row.fields.map(field => field.soap_destination))], quick_advanced_same_source: true, output_contract: { subjective: row.fields.filter(field => field.soap_destination === 'subjective').map(field => field.field_id), objective: row.fields.filter(field => field.soap_destination === 'objective').map(field => field.field_id), assessment: row.fields.filter(field => field.soap_destination === 'assessment').map(field => field.field_id), plan: row.fields.filter(field => field.soap_destination === 'plan').map(field => field.field_id) } }))
write('WORKFLOW_OUTPUTS_WAVE9.json', { schema_version: '1.0.0', records: outputs, fingerprint: hash(outputs) }); write('CATALOGUE_METADATA_WAVE9.json', { schema_version: '1.0.0', original_workflows: catalog.counts.original_workflows, active_workflows: catalog.counts.active_workflows, inactive_workflows: catalog.counts.inactive_workflows, clinician_facing_items: catalog.counts.clinician_facing_items, internal_evidence_records: catalog.counts.internal_evidence_records, interactive_fields: manifest.counts.fields, interactive_evidence_records_retained: manifest.counts.evidence_records_retained, fingerprint: hash({ catalog, manifest }) })
console.log(JSON.stringify({ status: 'PASS', outputs: outputs.length, active: catalog.counts.active_workflows, inactive: catalog.counts.inactive_workflows }, null, 2))
