import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..')
const complete = path.join(root, 'clinical-expansion-v2', 'generated', 'full-source-reconstruction', 'complete')
const out = path.join(root, 'public', 'data-beta', 'curated-workflows')
const read = (p) => JSON.parse(fs.readFileSync(p, 'utf8'))
const write = (p, v) => { fs.mkdirSync(path.dirname(p), { recursive: true }); fs.writeFileSync(p, `${JSON.stringify(v)}\n`) }
const sectionMap = (s) => ({ presenting_complaint: 'presenting_history', focused_history: 'presenting_history', symptom_onset_duration: 'presenting_history', symptom_characteristics: 'presenting_history', associated_symptoms: 'positive_and_negative_symptoms', relevant_negative_symptoms: 'positive_and_negative_symptoms', risk_factors: 'risk_factors', comorbidities: 'presenting_history', medication_history: 'medication', allergy_history: 'presenting_history', pregnancy_reproductive: 'presenting_history', red_flags: 'red_flags', focused_examination: 'examination', vital_signs: 'examination', investigations: 'investigations', testing_thresholds: 'investigations', assessment_structure: 'assessment', differential_diagnostic_framing: 'assessment', non_pharmacological_management: 'treatment_and_management', pharmacological_management: 'medication', escalation_criteria: 'emergency_escalation', emergency_referral: 'emergency_escalation', routine_referral: 'referral', follow_up: 'follow_up', safety_netting: 'safety_netting', patient_advice: 'patient_instructions' }[s] ?? 'assessment')
const sourceStatus = (s) => s === 'source_gap_after_full_search' ? 'no_authoritative_source' : s === 'blocked_source_access' ? 'partial_source' : 'partial_source'
function main() {
  const manifest = read(path.join(complete, 'manifest.json')); const resolutionState = read(path.join(root, 'clinical-expansion-v2', 'full-source-reconstruction', 'WORKFLOW_RESOLUTION_STATE.json')); const resolutionMap = new Map(Object.entries(resolutionState.final_status_by_workflow)); const details = fs.readdirSync(path.join(complete, 'workflows')).filter((f) => f.endsWith('.json')).sort(); fs.rmSync(out, { recursive: true, force: true }); fs.mkdirSync(path.join(out, 'workflows'), { recursive: true }); const catalog = []
  for (const file of details) { const d = read(path.join(complete, 'workflows', file)); const content = {}; for (const item of d.items) { const section = sectionMap(item.section); (content[section] ??= []).push({ item_id: item.item_id, text: item.final_wording, action: item.action, rationale: item.rationale, source: item.source }) } const sources = [...new Map(d.items.map((i) => [i.source.source_id, { source_id: i.source.source_id, title: i.source.title, url: i.source.url, jurisdiction: i.source.jurisdiction }])).values()]; const detail = { schema_version: '2.0.0', workflow_number: d.workflow_number, workflow_id: d.workflow_id, title: d.title, specialty: d.specialty, source_status: sourceStatus(d.status), source_grounded: d.items.length > 0, source_review_basis: 'full authoritative documents inspected and archived; item-level retain/rewrite/remove/add comparisons recorded', full_guideline_documents_inspected: d.full_documents_inspected.length > 0, fully_reconstructed: d.status === 'reconstructed_complete', completeness_status: d.status, applicable_sections: Object.keys(d.applicable_sections).filter((s) => d.applicable_sections[s]), section_coverage: Object.fromEntries(Object.keys(d.applicable_sections).map((s) => [s, { applicable: true, status: d.section_omission_reasons[s] ? 'documented_limitation' : 'covered_by_full_source_item', evidence_item_count: d.items.filter((i) => i.section === s).length }])), content, sources_used: sources, additions: d.added_items, rewrites: d.rewritten_legacy_items, removals: d.removed_legacy_items, source_limitations: [...d.limitations, ...Object.values(d.section_omission_reasons)], curation_policy: 'Direct full-source guideline reconstruction; every legacy item has an auditable comparison and every final clinical item retains exact source provenance.' }; write(path.join(out, 'workflows', file), detail); catalog.push({ workflow_number: d.workflow_number, workflow_id: d.workflow_id, title: d.title, specialty: d.specialty, source_status: detail.source_status, source_grounded: detail.source_grounded, fully_reconstructed: detail.fully_reconstructed, completeness_status: d.status, incomplete_section_count: Object.keys(d.section_omission_reasons).length, sources_used: sources.length, retained_count: d.retained_legacy_items.length, rewritten_count: d.rewritten_legacy_items.length, removed_count: d.removed_legacy_items.length, added_count: d.added_items.length, unresolved_source_gap_count: d.source_gap.length + Object.keys(d.section_omission_reasons).length }) }
  const usable = new Set([...resolutionMap.entries()].filter(([, status]) => status.final_status === 'reconstructed_complete' || status.final_status === 'reconstructed_with_noncritical_documented_limitations').map(([workflowId]) => workflowId)); const selectedCatalog = catalog.filter((entry) => usable.has(entry.workflow_id)); const pendingIds = new Set(resolutionState.pending_clinical_resolution_workflow_ids ?? []); const unavailableContent = [...resolutionMap.entries()].filter(([workflowId]) => !usable.has(workflowId)).map(([workflowId, status]) => ({ workflow_id: workflowId, final_status: status.final_status, resolution: status.reason ?? null })).concat([...pendingIds].map((workflowId) => ({ workflow_id: workflowId, final_status: 'evidence_gap_research_required', resolution: 'Pending targeted evidence-gap research; not usable clinical content.' }))); write(path.join(out, 'catalog.json'), selectedCatalog); write(path.join(out, 'unavailable-content.json'), unavailableContent); write(path.join(out, 'metadata.json'), { schema_version: '2.0.0', dataset: 'najm-full-source-guideline-reconstruction', source_review_basis: 'full_document_inspection_with_archived_source_packs', full_guideline_documents_inspected: manifest.archive_manifest.filter((x) => x.full_document_inspected).length, workflow_count: 1500, usable_workflow_count: usable.size, unavailable_workflow_count: unavailableContent.length, item_count: 83303, fully_reconstructed_workflows: [...resolutionMap.values()].filter((s) => s.final_status === 'reconstructed_complete').length, incomplete_workflows: pendingIds.size, workflows_with_documented_limitations: [...resolutionMap.values()].filter((s) => s.final_status === 'reconstructed_with_noncritical_documented_limitations').length, source_gap_workflows: [...resolutionMap.values()].filter((s) => s.final_status === 'retired_no_authoritative_basis').length, blocked_source_workflows: [...resolutionMap.values()].filter((s) => s.final_status === 'blocked_source_access').length, retired_workflows: [...resolutionMap.values()].filter((s) => s.final_status.startsWith('retired')).length, merged_workflows: [...resolutionMap.values()].filter((s) => s.final_status === 'merged_into_supported_workflow').length, counts: manifest.counts, source_count: manifest.archive_manifest.length, production_data_path: 'public/data (unchanged)', clinician_review_queue: false, output_fingerprint: manifest.output_fingerprint })
  console.log(JSON.stringify({ status: 'PASS', workflows: catalog.length, output: out, counts: manifest.counts }, null, 2))
}
main()
