// Evidence-gated structured controls for the 15 manually audited workflows.
// Each control is emitted only when its owning accepted evidence pack contains
// the declared anchor term; no clinical field is inferred from general knowledge.
export const manualStructuredFieldSpecs = {
  'cardio-chest-pain': [
    ['pain_location', 'Pain location', 'text', 'subjective', 'location'],
    ['pain_radiation', 'Pain radiation', 'text', 'subjective', 'radiat'],
    ['pain_severity', 'Pain severity', 'text', 'subjective', 'severity'],
    ['exertional_context', 'Exertional versus rest context', 'text', 'subjective', 'exertional'],
    ['associated_respiratory_symptoms', 'Associated respiratory symptoms', 'textarea', 'subjective', 'dyspnea'],
    ['red_flag_findings', 'Chest-pain red-flag findings', 'textarea', 'subjective', 'red flags'],
    ['haemodynamic_vitals', 'Haemodynamic observations', 'vital_sign', 'objective', 'haemodynamic'],
    ['cardiac_investigation_results', 'Cardiac investigation results', 'investigation_result', 'objective', 'troponin|ECG'],
    ['medication_history', 'Medication history', 'medication_entry', 'subjective', 'medication'],
    ['allergy_history', 'Allergy history', 'allergy_entry', 'subjective', 'allerg'],
    ['pregnancy_context', 'Pregnancy context', 'text', 'subjective', 'pregnan'],
  ],
  'gp-fever-urti': [
    ['fever_features', 'Fever features and pattern', 'textarea', 'subjective', 'fever'],
    ['temperature_measurement', 'Temperature measurement', 'vital_sign', 'objective', 'temperature'],
    ['cough_features', 'Cough features', 'text', 'subjective', 'cough'],
    ['hydration_status', 'Hydration status', 'examination_finding', 'objective', 'hydration'],
    ['travel_context', 'Travel context', 'text', 'subjective', 'travel'],
    ['vaccination_status', 'Vaccination status', 'text', 'subjective', 'vaccin'],
    ['pregnancy_context', 'Pregnancy context', 'text', 'subjective', 'pregnan'],
    ['rash_findings', 'Rash findings', 'examination_finding', 'objective', 'rash'],
    ['breathing_symptoms', 'Breathing symptoms', 'textarea', 'subjective', 'shortness of breath'],
    ['fever_investigation_results', 'Fever investigation results', 'investigation_result', 'objective', 'investig'],
  ],
  'ent-recurrent-tonsillitis': [
    ['sore_throat_features', 'Sore-throat features', 'textarea', 'subjective', 'sore throat'],
    ['tonsillar_findings', 'Tonsillar findings', 'examination_finding', 'objective', 'tonsil'],
    ['uvular_findings', 'Uvula findings', 'examination_finding', 'objective', 'uvul'],
    ['swallowing_difficulty', 'Swallowing difficulty', 'text', 'subjective', 'swallow'],
    ['cervical_node_findings', 'Cervical lymph-node findings', 'examination_finding', 'objective', 'cervical|lymph'],
    ['airway_findings', 'Airway findings', 'examination_finding', 'objective', 'airway'],
    ['fever_features', 'Fever features', 'text', 'subjective', 'fever'],
  ],
  'cardio-dyspnea': [
    ['oxygen_observation', 'Oxygenation observation', 'vital_sign', 'objective', 'oxygen|saturation'],
    ['respiratory_findings', 'Respiratory findings', 'examination_finding', 'objective', 'respiratory'],
    ['cardiac_investigation_results', 'Cardiac investigation results', 'investigation_result', 'objective', 'ECG'],
    ['pregnancy_context', 'Pregnancy context', 'text', 'subjective', 'pregnan'],
    ['blood_pressure_observation', 'Blood-pressure observation', 'vital_sign', 'objective', 'blood pressure|vital'],
  ],
  'gp-abdominal-pain': [
    ['abdominal_location', 'Abdominal pain location', 'text', 'subjective', 'abdominal'],
    ['pain_radiation', 'Pain radiation', 'text', 'subjective', 'radiat'],
    ['guarding_findings', 'Guarding findings', 'examination_finding', 'objective', 'guarding'],
    ['pregnancy_context', 'Pregnancy context', 'text', 'subjective', 'pregnan'],
    ['urinary_findings', 'Urinary findings', 'textarea', 'subjective', 'urine'],
    ['haematuria', 'Haematuria', 'text', 'subjective', 'haematuria'],
    ['pain_severity', 'Pain severity', 'text', 'subjective', 'severity'],
    ['blood_test_results', 'Blood-test results', 'investigation_result', 'objective', 'blood'],
  ],
  'gp-headache': [
    ['thunderclap_onset', 'Sudden or thunderclap onset', 'text', 'subjective', 'thunderclap'],
    ['neurological_findings', 'Neurological findings', 'examination_finding', 'objective', 'neurolog'],
    ['trauma_context', 'Head-trauma context', 'text', 'subjective', 'trauma'],
    ['visual_symptoms', 'Visual symptoms', 'textarea', 'subjective', 'visual'],
    ['seizure_context', 'Seizure context', 'text', 'subjective', 'seizure'],
    ['pregnancy_context', 'Pregnancy context', 'text', 'subjective', 'pregnan'],
    ['neck_stiffness', 'Neck-stiffness findings', 'examination_finding', 'objective', 'neck stiffness'],
  ],
  'cardio-hypertension-followup': [
    ['blood_pressure', 'Blood-pressure measurement', 'vital_sign', 'objective', 'blood pressure'],
    ['home_blood_pressure', 'Home blood-pressure readings', 'textarea', 'subjective', 'home'],
    ['adherence_structured', 'Medication adherence', 'textarea', 'subjective', 'adherence'],
    ['medication_dose', 'Medication dose and changes', 'medication_entry', 'subjective', 'dose'],
    ['renal_results', 'Renal-function results', 'investigation_result', 'objective', 'renal'],
    ['electrolyte_results', 'Electrolyte results', 'investigation_result', 'objective', 'electrolyte'],
    ['lipid_results', 'Lipid results', 'investigation_result', 'objective', 'lipid'],
    ['albumin_creatinine_results', 'Albumin/creatinine results', 'investigation_result', 'objective', 'albumin'],
    ['target_control', 'Target and control status', 'assessment_entry', 'assessment', 'target'],
  ],
  'gp-medication-adherence-review': [
    ['medication_entry', 'Medication name and regimen', 'medication_entry', 'subjective', 'medication'],
    ['adherence_structured', 'Medication adherence', 'textarea', 'subjective', 'adherence'],
    ['adverse_effects_structured', 'Adverse effects', 'textarea', 'subjective', 'adverse'],
    ['dose_route_frequency', 'Dose, route and frequency', 'medication_entry', 'subjective', 'dose|route|frequency'],
    ['allergy_history', 'Allergy history', 'allergy_entry', 'subjective', 'allerg'],
  ],
  'cardio-anticoagulation-documentation': [
    ['anticoagulation_indication', 'Anticoagulation indication', 'text', 'subjective', 'anticoag'],
    ['inr_result', 'INR result', 'investigation_result', 'objective', 'INR'],
    ['bleeding_history', 'Bleeding history', 'textarea', 'subjective', 'bleed'],
    ['renal_results', 'Renal-function results', 'investigation_result', 'objective', 'renal'],
    ['liver_results', 'Liver-function results', 'investigation_result', 'objective', 'liver'],
    ['adherence_structured', 'Anticoagulant adherence', 'textarea', 'subjective', 'adherence'],
    ['nsaid_use', 'NSAID use', 'text', 'subjective', 'NSAID'],
    ['antiplatelet_use', 'Antiplatelet use', 'text', 'subjective', 'antiplatelet'],
    ['thrombotic_symptoms', 'Thrombotic symptoms', 'textarea', 'subjective', 'thrombo'],
  ],
  'gp-medication-review': [
    ['medication_entry', 'Medication name and regimen', 'medication_entry', 'subjective', 'medication'],
    ['adherence_structured', 'Medication adherence', 'textarea', 'subjective', 'adherence'],
    ['adverse_effects_structured', 'Adverse effects', 'textarea', 'subjective', 'adverse'],
    ['allergy_history', 'Allergy history', 'allergy_entry', 'subjective', 'allerg'],
    ['dose_route_frequency', 'Dose, route and frequency', 'medication_entry', 'subjective', 'dose|frequency'],
  ],
  'cardio-ecg-result-review': [
    ['ecg_rhythm', 'ECG rhythm', 'text', 'objective', 'rhythm'],
    ['qrs_duration', 'QRS duration', 'text', 'objective', 'QRS'],
    ['cardiac_axis', 'Cardiac axis', 'text', 'objective', 'axis'],
    ['atrial_fibrillation', 'Atrial-fibrillation finding', 'text', 'objective', 'atrial fibrillation'],
    ['ecg_electrolytes', 'Electrolyte results', 'investigation_result', 'objective', 'electrolyte'],
    ['prior_ecg_comparison', 'Comparison with prior ECG', 'textarea', 'objective', 'comparison'],
    ['st_changes', 'ST-segment findings', 'text', 'objective', 'ST'],
  ],
  'ed-pediatric-fever-documentation': [
    ['temperature_measurement', 'Temperature measurement', 'vital_sign', 'objective', 'temperature'],
    ['age_context', 'Age context', 'text', 'subjective', 'age'],
    ['oxygen_observation', 'Oxygenation observation', 'vital_sign', 'objective', 'oxygen'],
    ['respiratory_rate', 'Respiratory rate', 'vital_sign', 'objective', 'respiratory rate'],
    ['heart_rate', 'Heart rate', 'vital_sign', 'objective', 'heart rate'],
    ['hydration_status', 'Hydration status', 'examination_finding', 'objective', 'hydration'],
    ['urine_output', 'Urine output', 'text', 'subjective', 'urine'],
    ['rash_findings', 'Rash findings', 'examination_finding', 'objective', 'rash'],
    ['seizure_context', 'Seizure context', 'text', 'subjective', 'seizure'],
    ['neck_stiffness', 'Neck-stiffness findings', 'examination_finding', 'objective', 'neck stiffness'],
    ['capillary_refill', 'Capillary-refill finding', 'examination_finding', 'objective', 'capillary'],
    ['glucose_result', 'Glucose result', 'investigation_result', 'objective', 'glucose'],
  ],
  'ed-observation-unit-review': [
    ['abcde_assessment', 'ABCDE assessment', 'examination_finding', 'objective', 'ABCDE'],
    ['sample_history', 'SAMPLE history', 'textarea', 'subjective', 'SAMPLE'],
    ['avpu_status', 'AVPU status', 'text', 'objective', 'AVPU'],
    ['gcs_status', 'GCS status', 'text', 'objective', 'GCS'],
    ['oxygen_observation', 'Oxygenation observation', 'vital_sign', 'objective', 'oxygen'],
    ['glucose_result', 'Glucose result', 'investigation_result', 'objective', 'glucose'],
    ['pregnancy_context', 'Pregnancy context', 'text', 'subjective', 'pregnancy'],
    ['trauma_context', 'Trauma context', 'text', 'subjective', 'trauma'],
    ['handover_transfer', 'Handover or transfer plan', 'referral_selection', 'plan', 'handover|transfer'],
    ['capillary_refill', 'Capillary-refill finding', 'examination_finding', 'objective', 'capillary'],
    ['vital_signs_structured', 'Vital signs', 'vital_sign', 'objective', 'vital'],
  ],
  'surg-bariatric-pre-operative-documentation': [
    ['anaesthetic_history', 'Previous anaesthetic history', 'textarea', 'subjective', 'anaesth'],
    ['allergy_history', 'Allergy history', 'allergy_entry', 'subjective', 'allerg'],
    ['body_mass_index', 'Body-mass index', 'vital_sign', 'objective', 'BMI'],
    ['weight', 'Weight', 'vital_sign', 'objective', 'weight'],
    ['asa_assessment', 'ASA assessment', 'assessment_entry', 'assessment', 'ASA'],
    ['laboratory_results', 'Laboratory results', 'investigation_result', 'objective', 'laboratory'],
  ],
  'surg-stoma-appliance-issue-documentation': [
    ['procedure_identity', 'Procedure identity', 'text', 'subjective', 'procedure'],
    ['consent', 'Consent documentation', 'text', 'subjective', 'consent'],
    ['procedure_complications', 'Procedure complications', 'examination_finding', 'objective', 'complication'],
    ['procedure_site', 'Procedure site', 'text', 'subjective', 'site'],
  ],
}
