// Second-wave controls for the manual-defect resolution.  These declarations
// are deliberately evidence-gated: the compiler emits a control only after an
// accepted evidence statement in the owning pack matches its anchor.
const s = (field_id, label, field_type, soap_destination, anchor, extra = {}) => ({
  field_id, label, field_type, soap_destination, anchor, ...extra,
})

const common = [
  s('age', 'Age', 'integer', 'subjective', 'age|years|months', { value_formatter: 'age' }),
  s('age_unit', 'Age unit', 'single_select', 'subjective', 'age|months|years', { options: ['years', 'months', 'weeks', 'days'], value_formatter: 'option' }),
  s('sex', 'Sex', 'single_select', 'subjective', '\\bsex\\b|female|male', { options: ['Female', 'Male', 'Intersex', 'Not recorded'], value_formatter: 'option' }),
  s('pregnancy_status', 'Pregnancy or postpartum status', 'single_select', 'subjective', 'pregnan|postpartum', { options: ['Pregnant', 'Not pregnant', 'Postpartum', 'Unknown'], value_formatter: 'option', contradictory_option_rules: ['pregnancy_status=Pregnant'] }),
  s('encounter_setting', 'Encounter setting', 'single_select', 'subjective', 'setting|primary care|emergency|outpatient', { options: ['Outpatient', 'Urgent assessment', 'Emergency', 'Inpatient', 'Telephone'], value_formatter: 'option' }),
  s('onset', 'Onset', 'text', 'subjective', 'onset|sudden|gradual', { value_formatter: 'trimmed_text' }),
  s('duration', 'Duration', 'duration', 'subjective', 'duration|days|hours|weeks', { value_formatter: 'duration' }),
  s('severity', 'Severity', 'single_select', 'subjective', 'severity|mild|moderate|severe', { options: ['Mild', 'Moderate', 'Severe', 'Not assessed'], value_formatter: 'option' }),
  s('medication_reconciliation', 'Medication reconciliation', 'medication_entry', 'subjective', 'medication|prescri|dose|route|frequency', { value_formatter: 'medication' }),
  s('allergy_reaction', 'Allergy and reaction', 'allergy_entry', 'subjective', 'allerg|reaction|hypersens', { value_formatter: 'allergy' }),
  s('follow_up_interval', 'Follow-up interval', 'follow_up_selection', 'plan', 'follow-up|review|reassess', { options: ['Within 24 hours', 'Within 48 hours', 'Within 7 days', 'Routine review', 'As needed'], value_formatter: 'option' }),
  s('disposition', 'Disposition', 'referral_selection', 'plan', 'disposition|refer|escalat|admit|discharge', { options: ['Continue outpatient care', 'Urgent review', 'Emergency referral', 'Admit', 'Discharge with advice'], value_formatter: 'option' }),
  s('safety_netting', 'Safety-netting', 'safety_netting_selection', 'plan', 'safety-net|red flag|seek urgent', { options: ['Return if worse', 'Seek urgent review', 'Call emergency services', 'No safety-net recorded'], value_formatter: 'option' }),
]

const acute = [
  s('symptom_location', 'Symptom location', 'text', 'subjective', 'location|site|localis'),
  s('symptom_laterality', 'Laterality', 'single_select', 'subjective', 'left|right|unilateral|bilateral|laterality', { options: ['Left', 'Right', 'Bilateral', 'Midline', 'Not applicable', 'Unknown'], value_formatter: 'option' }),
  s('symptom_character', 'Symptom character', 'text', 'subjective', 'character|quality|nature'),
  s('associated_symptoms_detail', 'Associated symptoms', 'textarea', 'subjective', 'associated symptom|symptoms'),
  s('red_flag_assessment', 'Red-flag assessment', 'yes_no_unknown', 'subjective', 'red flag|warning sign|urgent', { options: ['Yes', 'No', 'Unknown'], value_formatter: 'option' }),
  s('vital_signs_structured', 'Vital signs', 'vital_sign', 'objective', 'vital|temperature|heart rate|blood pressure|oxygen|respiratory rate', { value_formatter: 'vital_sign' }),
  s('examination_findings_structured', 'Examination findings', 'examination_finding', 'objective', 'examination|physical finding|clinical finding', { value_formatter: 'examination' }),
  s('investigation_value', 'Investigation result and comparison', 'investigation_result', 'objective', 'investigation|result|value|comparison', { value_formatter: 'investigation' }),
  s('clinician_assessment', 'Clinician assessment', 'assessment_entry', 'assessment', 'assessment|impression|interpret', { value_formatter: 'assessment' }),
  s('plan_action', 'Plan action', 'plan_entry', 'plan', 'plan|management|treatment|action', { value_formatter: 'plan' }),
]

const specs = {
  'cardio-chest-pain': [
    ...common, ...acute,
    s('pain_onset_pattern', 'Pain onset pattern', 'single_select', 'subjective', 'onset|sudden|gradual', { options: ['Sudden', 'Gradual', 'Intermittent', 'Continuous', 'Unknown'], value_formatter: 'option' }),
    s('pain_exertional_context', 'Exertional or rest context', 'single_select', 'subjective', 'exertional|rest', { options: ['Exertional', 'At rest', 'Both', 'Unknown'], value_formatter: 'option' }),
    s('dyspnoea', 'Shortness of breath', 'yes_no_unknown', 'subjective', 'dyspnea|shortness of breath', { options: ['Yes', 'No', 'Unknown'], value_formatter: 'option' }),
    s('cardiac_investigation_value', 'ECG/troponin result', 'investigation_result', 'objective', 'ECG|troponin|cardiac', { value_formatter: 'investigation' }),
  ],
  'gp-fever-urti': [
    ...common, ...acute,
    s('temperature', 'Measured temperature', 'vital_sign', 'objective', 'temperature|fever', { value_formatter: 'vital_sign' }),
    s('fever_pattern', 'Fever pattern', 'single_select', 'subjective', 'pattern|intermittent|continuous', { options: ['Intermittent', 'Continuous', 'Unknown'], value_formatter: 'option' }),
    s('cough', 'Cough', 'single_select', 'subjective', 'cough', { options: ['Present', 'Absent', 'Unknown'], value_formatter: 'option' }),
    s('hydration', 'Hydration and oral intake', 'examination_finding', 'objective', 'hydration|intake|dehydrat', { value_formatter: 'examination' }),
    s('rash', 'Rash findings', 'examination_finding', 'objective', 'rash', { value_formatter: 'examination' }),
    s('travel_and_contacts', 'Travel or sick-contact history', 'textarea', 'subjective', 'travel|contact|outbreak'),
    s('respiratory_red_flags', 'Breathing difficulty', 'yes_no_unknown', 'subjective', 'shortness of breath|breathing difficulty|respiratory distress', { options: ['Yes', 'No', 'Unknown'], value_formatter: 'option' }),
  ],
  'ent-recurrent-tonsillitis': [
    ...common, ...acute,
    s('sore_throat_severity', 'Sore-throat severity', 'single_select', 'subjective', 'severity|pain', { options: ['Mild', 'Moderate', 'Severe', 'Unknown'], value_formatter: 'option' }),
    s('swallowing', 'Swallowing difficulty', 'single_select', 'subjective', 'swallow|odynophagia|dysphagia', { options: ['No difficulty', 'Difficulty', 'Unable to swallow', 'Unknown'], value_formatter: 'option' }),
    s('airway_observation', 'Airway and voice', 'examination_finding', 'objective', 'airway|voice|drool|trismus|uvula', { value_formatter: 'examination' }),
    s('tonsil_examination', 'Tonsillar examination', 'examination_finding', 'objective', 'tonsil|exudate|pharyn', { value_formatter: 'examination' }),
    s('cervical_nodes', 'Cervical lymph nodes', 'examination_finding', 'objective', 'cervical|lymph node', { value_formatter: 'examination' }),
  ],
  'cardio-dyspnea': [
    ...common, ...acute,
    s('breathlessness_context', 'Breathlessness at rest or exertion', 'single_select', 'subjective', 'rest|exertion|breathlessness|dyspnea', { options: ['At rest', 'On exertion', 'Both', 'Unknown'], value_formatter: 'option' }),
    s('orthopnoea_pnd', 'Orthopnoea or nocturnal dyspnoea', 'yes_no_unknown', 'subjective', 'orthopnoea|paroxysmal|nocturnal', { options: ['Yes', 'No', 'Unknown'], value_formatter: 'option' }),
    s('wheeze_sputum', 'Wheeze or sputum', 'textarea', 'subjective', 'wheeze|sputum|cough'),
    s('respiratory_examination', 'Respiratory examination', 'examination_finding', 'objective', 'respiratory examination|chest examination|crepitation', { value_formatter: 'examination' }),
    s('oxygen_saturation', 'Oxygen saturation', 'vital_sign', 'objective', 'oxygen|saturation', { value_formatter: 'vital_sign' }),
    s('ecg_result', 'ECG result', 'investigation_result', 'objective', 'ECG', { value_formatter: 'investigation' }),
  ],
  'gp-abdominal-pain': [
    ...common, ...acute,
    s('abdominal_quadrant', 'Abdominal location and laterality', 'single_select', 'subjective', 'abdominal|quadrant|location', { options: ['Right upper', 'Left upper', 'Right lower', 'Left lower', 'Central', 'Diffuse', 'Unknown'], value_formatter: 'option' }),
    s('radiation', 'Pain radiation', 'text', 'subjective', 'radiat'),
    s('urinary_gynaecological', 'Urinary or gynaecological symptoms', 'textarea', 'subjective', 'urine|urinary|vaginal|menstrual|LMP'),
    s('guarding_peritonism', 'Guarding or peritonism', 'examination_finding', 'objective', 'guarding|periton|abdomen', { value_formatter: 'examination' }),
    s('blood_test_result', 'Blood-test result', 'investigation_result', 'objective', 'blood test|haemat|CRP|renal|liver', { value_formatter: 'investigation' }),
  ],
  'gp-headache': [
    ...common, ...acute,
    s('thunderclap', 'Sudden or thunderclap onset', 'yes_no_unknown', 'subjective', 'thunderclap|sudden', { options: ['Yes', 'No', 'Unknown'], value_formatter: 'option' }),
    s('first_worst', 'First or worst headache', 'yes_no_unknown', 'subjective', 'first|worst|new headache', { options: ['Yes', 'No', 'Unknown'], value_formatter: 'option' }),
    s('progression', 'Progression or previous similar episodes', 'textarea', 'subjective', 'progress|previous|similar'),
    s('neurological_exam', 'Neurological examination', 'examination_finding', 'objective', 'neurolog|cranial|fundoscop|mening', { value_formatter: 'examination' }),
    s('visual_symptoms', 'Visual symptoms', 'textarea', 'subjective', 'visual|diplopia|vision'),
    s('headache_imaging', 'Imaging or blood-test result', 'investigation_result', 'objective', 'imaging|blood test|result', { value_formatter: 'investigation' }),
  ],
  'cardio-hypertension-followup': [
    ...common,
    s('blood_pressure_reading', 'Blood-pressure reading', 'vital_sign', 'objective', 'blood pressure|BP', { value_formatter: 'vital_sign' }),
    s('home_bp', 'Home blood-pressure readings', 'investigation_result', 'objective', 'home blood pressure|home BP', { value_formatter: 'investigation' }),
    s('diagnosis_duration', 'Diagnosis date or duration', 'duration', 'subjective', 'diagnos|duration|years'),
    s('adherence', 'Adherence and missed doses', 'single_select', 'subjective', 'adherence|missed dose', { options: ['Good', 'Missed doses', 'Unable to assess', 'Unknown'], value_formatter: 'option' }),
    s('adverse_effects', 'Adverse effects', 'textarea', 'subjective', 'adverse|side effect'),
    s('renal_electrolyte', 'Renal and electrolyte result', 'investigation_result', 'objective', 'renal|electrolyte|creatinine|potassium', { value_formatter: 'investigation' }),
    s('lipid_acr', 'Lipid or albumin-creatinine result', 'investigation_result', 'objective', 'lipid|albumin|ACR', { value_formatter: 'investigation' }),
    s('control_assessment', 'Control classification', 'single_select', 'assessment', 'control|target|normal|uncontrolled', { options: ['At target', 'Above target', 'Below target', 'Unknown'], value_formatter: 'option' }),
  ],
  'gp-medication-adherence-review': [
    ...common,
    s('medication_name', 'Medication name', 'medication_entry', 'subjective', 'medication|drug|medicine', { value_formatter: 'medication' }),
    s('dose_route_frequency', 'Dose, route and frequency', 'medication_entry', 'subjective', 'dose|route|frequency', { value_formatter: 'medication' }),
    s('adherence', 'Adherence and missed doses', 'single_select', 'subjective', 'adherence|missed dose', { options: ['Taking as prescribed', 'Missed doses', 'Stopped', 'Unknown'], value_formatter: 'option' }),
    s('adverse_effect', 'Adverse effect linked to medicine', 'textarea', 'subjective', 'adverse|side effect'),
    s('allergy_reaction_detail', 'Allergy and reaction detail', 'allergy_entry', 'subjective', 'allerg|reaction', { value_formatter: 'allergy' }),
    s('medication_decision', 'Medication decision', 'single_select', 'plan', 'continue|adjust|switch|stop', { options: ['Continue', 'Adjust', 'Switch', 'Stop', 'Unknown'], value_formatter: 'option' }),
  ],
  'cardio-anticoagulation-documentation': [
    ...common,
    s('indication', 'Anticoagulation indication', 'single_select', 'subjective', 'atrial fibrillation|VTE|thrombo|valve|anticoag', { options: ['Atrial fibrillation', 'Venous thromboembolism', 'Mechanical valve', 'Other documented indication', 'Unknown'], value_formatter: 'option' }),
    s('anticoagulant_regimen', 'Anticoagulant, dose and frequency', 'medication_entry', 'subjective', 'anticoagul|dose|frequency', { value_formatter: 'medication' }),
    s('inr', 'INR result', 'investigation_result', 'objective', 'INR|therapeutic range', { value_formatter: 'investigation' }),
    s('bleeding', 'Bleeding symptoms', 'examination_finding', 'objective', 'bleed|bruis|haematur|melaena', { value_formatter: 'examination' }),
    s('thrombosis', 'Thrombotic symptoms', 'textarea', 'subjective', 'thrombo|leg swelling|chest pain|shortness'),
    s('interaction_review', 'Interaction review', 'textarea', 'subjective', 'NSAID|antiplatelet|interact|herbal'),
    s('renal_liver_fbc', 'Renal, liver or full-blood-count result', 'investigation_result', 'objective', 'renal|liver|full blood|FBC', { value_formatter: 'investigation' }),
    s('dose_plan', 'Dose adjustment or continuation', 'single_select', 'plan', 'dose adjustment|continue|interrupt|hold', { options: ['Continue', 'Adjust dose', 'Interrupt', 'Urgent review', 'Unknown'], value_formatter: 'option' }),
  ],
  'gp-medication-review': [
    ...common,
    s('current_medication', 'Current medication', 'medication_entry', 'subjective', 'medication|drug|prescrib', { value_formatter: 'medication' }),
    s('indication', 'Medication indication', 'text', 'subjective', 'indication|reason'),
    s('adherence', 'Adherence and access', 'textarea', 'subjective', 'adherence|access|missed'),
    s('adverse_effect', 'Adverse effect and linked medicine', 'textarea', 'subjective', 'adverse|side effect'),
    s('allergy_reaction_detail', 'Allergy and reaction', 'allergy_entry', 'subjective', 'allerg|reaction', { value_formatter: 'allergy' }),
    s('medication_plan', 'Medication continuation or change', 'single_select', 'plan', 'continue|adjust|switch|stop', { options: ['Continue', 'Adjust', 'Switch', 'Stop', 'Unknown'], value_formatter: 'option' }),
  ],
  'cardio-ecg-result-review': [
    ...common,
    s('ecg_date', 'ECG date', 'date', 'objective', 'date|performed|ECG'),
    s('ecg_reason', 'Reason ECG was performed', 'text', 'subjective', 'reason|indication|symptom'),
    s('heart_rate', 'Heart rate', 'vital_sign', 'objective', 'heart rate|rate|bpm', { value_formatter: 'vital_sign' }),
    s('rhythm', 'Rhythm', 'single_select', 'objective', 'rhythm|sinus|atrial fibrillation|paced', { options: ['Sinus rhythm', 'Atrial fibrillation/flutter', 'Paced rhythm', 'Other documented rhythm', 'Unknown'], value_formatter: 'option' }),
    s('intervals_axis', 'Intervals and cardiac axis', 'investigation_result', 'objective', 'PR|QRS|QT|axis|interval', { value_formatter: 'investigation' }),
    s('st_t_q_findings', 'ST, T-wave or Q-wave findings', 'examination_finding', 'objective', 'ST|T-wave|Q wave|abnormal', { value_formatter: 'examination' }),
    s('auto_interpretation', 'Automated ECG interpretation', 'textarea', 'objective', 'automated interpretation|machine'),
    s('clinician_interpretation', 'Clinician ECG interpretation', 'assessment_entry', 'assessment', 'clinician interpretation|interpretation|impression', { value_formatter: 'assessment' }),
    s('prior_comparison', 'Comparison with prior ECG', 'investigation_result', 'objective', 'comparison|previous ECG|prior', { value_formatter: 'investigation' }),
    s('ecg_action', 'ECG follow-up action', 'single_select', 'plan', 'repeat ECG|cardiology|urgent|follow-up', { options: ['No further action', 'Repeat ECG', 'Additional testing', 'Cardiology referral', 'Urgent escalation', 'Unknown'], value_formatter: 'option' }),
  ],
  'ed-pediatric-fever-documentation': [
    ...common,
    s('temperature_method', 'Temperature and measurement method', 'vital_sign', 'objective', 'temperature|method|fever', { value_formatter: 'vital_sign' }),
    s('respiratory_rate', 'Respiratory rate', 'vital_sign', 'objective', 'respiratory rate|RR', { value_formatter: 'vital_sign' }),
    s('heart_rate', 'Heart rate', 'vital_sign', 'objective', 'heart rate|HR', { value_formatter: 'vital_sign' }),
    s('oxygen_saturation', 'Oxygen saturation', 'vital_sign', 'objective', 'oxygen|saturation', { value_formatter: 'vital_sign' }),
    s('weight', 'Weight', 'vital_sign', 'objective', 'weight|kg', { value_formatter: 'vital_sign' }),
    s('hydration_intake', 'Hydration and oral intake', 'examination_finding', 'objective', 'hydration|intake|urine|dehydrat', { value_formatter: 'examination' }),
    s('rash_neuro_resp', 'Rash, neurological or respiratory findings', 'examination_finding', 'objective', 'rash|seizure|neck stiffness|airway|respiratory', { value_formatter: 'examination' }),
    s('capillary_refill', 'Capillary refill', 'vital_sign', 'objective', 'capillary refill|perfusion', { value_formatter: 'vital_sign' }),
    s('paediatric_disposition', 'Paediatric disposition', 'referral_selection', 'plan', 'disposition|admit|discharge|safety-net', { options: ['Observe', 'Discharge with safety-net', 'Urgent paediatric review', 'Admit', 'Unknown'], value_formatter: 'option' }),
  ],
  'ed-observation-unit-review': [
    ...common,
    s('abcde_assessment', 'ABCDE assessment', 'examination_finding', 'objective', 'ABCDE|airway|breathing|circulation|disability|exposure', { value_formatter: 'examination' }),
    s('avpu_gcs', 'AVPU or GCS', 'vital_sign', 'objective', 'AVPU|GCS|conscious', { value_formatter: 'vital_sign' }),
    s('emergency_vitals', 'Emergency vital signs', 'vital_sign', 'objective', 'vital|oxygen|blood pressure|glucose', { value_formatter: 'vital_sign' }),
    s('emergency_investigation', 'Emergency investigation result', 'investigation_result', 'objective', 'ECG|blood|gas|urine|imaging|result', { value_formatter: 'investigation' }),
    s('immediate_treatment', 'Immediate treatment and response', 'plan_entry', 'plan', 'treatment|oxygen|fluid|monitor|response', { value_formatter: 'plan' }),
    s('handover_disposition', 'Handover and disposition', 'referral_selection', 'plan', 'handover|disposition|refer|admit|discharge', { options: ['Continue observation', 'Senior review', 'Admit', 'Transfer', 'Discharge', 'Unknown'], value_formatter: 'option' }),
  ],
  'surg-bariatric-pre-operative-documentation': [
    ...common,
    s('planned_procedure', 'Planned procedure', 'text', 'subjective', 'procedure|operation|surgery'),
    s('anaesthetic_history', 'Anaesthetic history and airway', 'examination_finding', 'objective', 'anaesth|airway|PONV|intubat', { value_formatter: 'examination' }),
    s('weight_height_bmi', 'Weight, height and BMI', 'vital_sign', 'objective', 'weight|height|BMI', { value_formatter: 'vital_sign' }),
    s('asa_classification', 'ASA classification', 'single_select', 'assessment', 'ASA|classification', { options: ['ASA I', 'ASA II', 'ASA III', 'ASA IV', 'ASA V', 'Not assigned'], value_formatter: 'option' }),
    s('preop_investigation', 'Pre-operative investigation result', 'investigation_result', 'objective', 'investigation|ECG|laboratory|result', { value_formatter: 'investigation' }),
    s('consent_and_fasting', 'Consent and fasting status', 'textarea', 'subjective', 'consent|fasting'),
    s('anaesthetic_plan', 'Anaesthetic plan', 'plan_entry', 'plan', 'anaesthetic plan|airway plan|monitor', { value_formatter: 'plan' }),
  ],
  'surg-stoma-appliance-issue-documentation': [
    ...common,
    s('procedure_identity', 'Procedure or stoma issue identity', 'text', 'subjective', 'procedure|stoma|appliance'),
    s('site_laterality', 'Site and laterality', 'text', 'subjective', 'site|left|right|location'),
    s('stoma_findings', 'Stoma or wound findings', 'examination_finding', 'objective', 'stoma|wound|examination|finding', { value_formatter: 'examination' }),
    s('complication', 'Complication', 'single_select', 'assessment', 'complication|bleed|infection', { options: ['None documented', 'Bleeding', 'Infection', 'Other documented complication', 'Unknown'], value_formatter: 'option' }),
    s('consent', 'Consent or time-out', 'single_select', 'subjective', 'consent|time-out', { options: ['Completed', 'Not completed', 'Not applicable'], value_formatter: 'option' }),
    s('procedure_result', 'Procedure result and aftercare', 'plan_entry', 'plan', 'aftercare|follow-up|result|outcome', { value_formatter: 'plan' }),
  ],
}

export const resolutionStructuredFieldSpecs = specs

