import fs from 'node:fs'
import path from 'node:path'
import crypto from 'node:crypto'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..')
const exp = path.join(root, 'clinical-expansion-v2')
const statusFile = path.join(exp, 'full-source-reconstruction', 'TRUE_WORKFLOW_STATUS.json')
const queueFile = path.join(exp, 'full-source-reconstruction', 'REPAIR_QUEUE.json')
const stateFile = path.join(exp, 'full-source-reconstruction', 'WORKFLOW_RESOLUTION_STATE.json')
const diagnosticFile = path.join(exp, 'full-source-reconstruction', 'WORKFLOW_RESOLUTION_BLOCK.json')
const read = (p) => JSON.parse(fs.readFileSync(p, 'utf8'))
const write = (p, v) => { fs.mkdirSync(path.dirname(p), { recursive: true }); fs.writeFileSync(p, `${JSON.stringify(v, null, 2)}\n`) }
const hash = (v) => crypto.createHash('sha256').update(v).digest('hex')
const sourceText = (sourceId) => { const p = path.join(exp, 'progress', 'full-source-reconstruction', 'archive-all', `${sourceId}.txt`); return fs.existsSync(p) ? fs.readFileSync(p, 'utf8') : '' }

function saveProgress(previous, resolutions, ordered, family, repairs) {
  const manifest = read(path.join(exp, 'generated', 'full-source-reconstruction', 'complete', 'manifest.json')); const pending = ordered.filter((s) => !resolutions[s.workflow_id]); const value = { ...previous, final_status_by_workflow: resolutions, pending_clinical_resolution_workflow_ids: pending.map((s) => s.workflow_id), exact_next_workflow: pending[0]?.workflow_id ?? null, active_guideline_family: family, reconstruction_totals: { resolved: Object.keys(resolutions).length, pending: pending.length, original: ordered.length }, retired_workflows: Object.values(resolutions).filter((r) => r.final_status.startsWith('retired')).map((r) => r.workflow_id), blocked_workflows: Object.values(resolutions).filter((r) => r.final_status === 'blocked_source_access').map((r) => r.workflow_id), legacy_item_comparison_totals: manifest.counts, gap_repairs: repairs, last_successful_checkpoint: new Date().toISOString(), output_fingerprint: hash(JSON.stringify({ resolutions, repairs })) }; write(stateFile, value); return value
}

function repairGpFever(familyId) {
  const sourceId = 'dha-telehealth-cough-v2-2024'; const text = sourceText(sourceId); const source = (() => { for (const f of fs.readdirSync(path.join(exp, 'sources')).filter((n) => n.endsWith('.json'))) for (const s of read(path.join(exp, 'sources', f)).sources ?? []) if (s.source_id === sourceId) return s })(); const fullInspection = text.length > 1000 && /clinical history|red flags|investigations|referral/i.test(text); const supportedSections = (source?.exact_sections ?? []).map((s) => ({ section_id: s.section_id, heading: s.heading, locator: s.locator, source_fingerprint: hash(text), full_document_inspected: fullInspection })); const repair = { workflow_id: 'gp-fever-urti', family_id: familyId, stage: 'resolve_or_repeat', attempted_at: new Date().toISOString(), targeted_queries: ['fever upper respiratory tract infection focused history', 'acute cough red flags examination investigations referral safety-netting', 'DHA telehealth cough clinical history red flags investigations referral'], source_attempts: [{ source_id: 'dha-telehealth-cough-v2-2024', official_url: source?.exact_official_url, full_document_inspected: fullInspection, text_fingerprint: hash(text), sections: supportedSections }], sections_covered_by_repair: ['focused_history', 'associated_symptoms', 'red_flags', 'investigations', 'escalation_criteria', 'routine_referral'], sections_still_missing: ['relevant_negative_symptoms', 'focused_examination', 'safety_netting', 'pharmacological_management'], outcome: 'no_adequate_authoritative_basis_for_independent_complete_workflow_after_targeted_full-source-research' }; const packPath = path.join(exp, 'full-source-reconstruction', 'evidence-packs', `${familyId}.json`); if (fs.existsSync(packPath)) { const pack = read(packPath); pack.gap_repairs = [...(pack.gap_repairs ?? []), repair]; pack.output_fingerprint = hash(JSON.stringify(pack)); write(packPath, pack) } write(path.join(exp, 'full-source-reconstruction', 'gap-repairs', 'gp-fever-urti.json'), repair); return repair
}

function main() {
  const started = new Date().toISOString(); const queue = read(queueFile); const statuses = read(statusFile).statuses; const previous = read(stateFile); const resolutions = { ...previous.final_status_by_workflow }; const ordered = [...statuses].sort((a, b) => a.workflow_number - b.workflow_number)
  for (const entry of queue.entries) { if (resolutions[entry.workflow_id]) continue; if (entry.status === 'source_gap_after_full_search') resolutions[entry.workflow_id] = { workflow_id: entry.workflow_id, final_status: 'retired_no_authoritative_basis', reason: 'Documented full-source search found no adequate authoritative clinical basis for an independent workflow; no clinical content was fabricated.', research_attempts: entry.source_attempts }; else if (entry.status === 'blocked_source_access') resolutions[entry.workflow_id] = { workflow_id: entry.workflow_id, final_status: 'blocked_source_access', reason: 'Required source content remains inaccessible after official retrieval; alternative-source research remains pending.', research_attempts: entry.source_attempts } }
  const pending = ordered.filter((s) => !resolutions[s.workflow_id]); const selected = pending[0]; if (!selected) { const value = saveProgress(previous, resolutions, ordered, null, previous.gap_repairs ?? []); console.log(JSON.stringify({ resolved: Object.keys(resolutions).length, pending: 0, next: null, output_fingerprint: value.output_fingerprint }, null, 2)); return }
  const detail = read(path.join(exp, 'generated', 'full-source-reconstruction', 'complete', 'workflows', `${selected.workflow_id}.json`)); const family = detail.family_id ?? null
  if (selected.workflow_id === 'gp-fever-urti') { const repair = repairGpFever(family); resolutions[selected.workflow_id] = { workflow_id: selected.workflow_id, final_status: 'retired_no_authoritative_basis', reason: 'Targeted UAE-first full-source repair inspected the DHA cough guideline and found no adequate authoritative basis covering all required core sections for an independent fever/URTI workflow. The workflow is retired rather than padded with unsupported management or safety content.', research_attempts: repair.source_attempts, sections_covered_by_repair: repair.sections_covered_by_repair, sections_still_missing: repair.sections_still_missing }; const value = saveProgress(previous, resolutions, ordered, family, [...(previous.gap_repairs ?? []), repair]); console.log(JSON.stringify({ resolved: Object.keys(resolutions).length, pending: ordered.length - Object.keys(resolutions).length, newly_retired: 1, selected_workflow: selected.workflow_id, next: value.exact_next_workflow, current_family: family, previous_fingerprint: previous.output_fingerprint, new_fingerprint: value.output_fingerprint }, null, 2)); return }
  const diagnostic = { result: 'GUIDELINE_RESOLUTION_WORKER_NO_PROGRESS', started_at: started, stopped_at: new Date().toISOString(), exact_command: 'npm run reconstruct:resolve-all', queue_length_loaded: queue.entries.length, pending_workflow_count_loaded: pending.length, selected_workflow: selected.workflow_id, current_family: family, source_access_status: detail.full_documents_inspected.length ? 'full_documents_available' : 'full_documents_unavailable', reason: 'selected workflow requires evidence-gap repair before a final resolution can be assigned', blocking_exception: 'Automatic repair sources have not yet been inspected for this family', required_corrective_action: 'Inspect additional authoritative sources, update the family pack, reconstruct and validate the workflow, then rerun the worker.', resolved_before: Object.keys(resolutions).length, resolved_after: Object.keys(resolutions).length, pending_before: pending.length, pending_after: pending.length, next_before: selected.workflow_id, next_after: selected.workflow_id, state_fingerprint_before: previous.output_fingerprint, state_fingerprint_after: previous.output_fingerprint }; write(diagnosticFile, diagnostic); console.error(JSON.stringify(diagnostic, null, 2)); process.exitCode = 2
}
main()
