import fs from 'node:fs'
import path from 'node:path'
import crypto from 'node:crypto'
import { execFileSync } from 'node:child_process'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..')
const exp = path.join(root, 'clinical-expansion-v2')
const workflowDir = path.join(exp, 'workflows')
const researchDir = path.join(exp, 'research')
const sourceDir = path.join(exp, 'sources')
const outRoot = path.join(exp, 'generated', 'full-source-reconstruction', 'complete')
const archiveRoot = path.join(exp, 'progress', 'full-source-reconstruction', 'archive-all')
const packRoot = path.join(exp, 'full-source-reconstruction', 'evidence-packs')
const familyRoot = path.join(exp, 'progress', 'full-source-reconstruction', 'families')
const read = (p) => JSON.parse(fs.readFileSync(p, 'utf8'))
const write = (p, v) => { fs.mkdirSync(path.dirname(p), { recursive: true }); fs.writeFileSync(p, `${JSON.stringify(v, null, 2)}\n`) }
const sha = (v) => crypto.createHash('sha256').update(v).digest('hex')
const files = (p, suffix) => fs.readdirSync(p).filter((n) => n.endsWith(suffix)).sort()
const safe = (v) => String(v).replace(/[^a-z0-9._-]+/gi, '_')
const sourceMap = new Map(files(sourceDir, '.json').flatMap((f) => read(path.join(sourceDir, f)).sources ?? []).map((s) => [s.source_id, s]))
const workflows = files(workflowDir, '.json').map((f) => read(path.join(workflowDir, f))).sort((a, b) => a.baseline.source_workflow_index - b.baseline.source_workflow_index)
const research = new Map(files(researchDir, '.research.json').map((f) => read(path.join(researchDir, f))).map((r) => [r.workflow_id, r]))
const existingArchive = new Map()
for (const rootDir of [path.join(exp, 'progress', 'full-source-reconstruction', 'archive'), archiveRoot]) {
  if (!fs.existsSync(rootDir)) continue
  for (const f of fs.readdirSync(rootDir).filter((n) => n.endsWith('.txt'))) existingArchive.set(f.replace(/\.txt$/, ''), path.join(rootDir, f))
}
function extract(file) { try { return execFileSync('pdf2txt.py', [file], { encoding: 'utf8', env: { ...process.env, PYTHONIOENCODING: 'utf-8' }, maxBuffer: 40 * 1024 * 1024 }) } catch { return fs.readFileSync(file, 'utf8') } }
async function archive(source) {
  const key = safe(source.source_id); const txt = path.join(archiveRoot, `${key}.txt`); const old = existingArchive.get(key)
  if (old && fs.existsSync(old)) { const text = fs.readFileSync(old, 'utf8'); const bytes = fs.existsSync(old.replace(/\.txt$/, '.pdf')) ? fs.readFileSync(old.replace(/\.txt$/, '.pdf')) : Buffer.from(text); fs.mkdirSync(archiveRoot, { recursive: true }); fs.copyFileSync(old, txt); return { source_id: source.source_id, title: source.exact_document_title, publisher: source.issuing_organisation, jurisdiction: source.jurisdiction, population: source.population, setting: source.clinical_setting, official_url: source.exact_official_url, accessed_on: fs.statSync(old).mtime.toISOString(), document_type: bytes.subarray(0, 4).toString() === '%PDF' ? 'PDF' : 'TEXT', archived_filename: path.relative(root, old).replaceAll('\\', '/'), text_filename: path.relative(root, txt).replaceAll('\\', '/'), content_sha256: sha(bytes), extracted_text_sha256: sha(text), extracted_text_length: text.length, full_document_inspected: text.length > 1000, retrieval_status: 'reused_archived_full_text' } }
  try {
    const res = await fetch(source.exact_official_url, { redirect: 'follow', signal: AbortSignal.timeout(45000) }); if (!res.ok) throw new Error(`HTTP ${res.status}`)
    const bytes = Buffer.from(await res.arrayBuffer()); const pdf = res.headers.get('content-type')?.includes('pdf') || bytes.subarray(0, 4).toString() === '%PDF'; const ext = pdf ? 'pdf' : 'html'; const bin = path.join(archiveRoot, `${key}.${ext}`); fs.mkdirSync(archiveRoot, { recursive: true }); fs.writeFileSync(bin, bytes); const text = pdf ? extract(bin) : bytes.toString('utf8'); fs.writeFileSync(txt, text)
    return { source_id: source.source_id, title: source.exact_document_title, publisher: source.issuing_organisation, jurisdiction: source.jurisdiction, population: source.population, setting: source.clinical_setting, official_url: source.exact_official_url, accessed_on: new Date().toISOString(), document_type: pdf ? 'PDF' : 'HTML', archived_filename: path.relative(root, bin).replaceAll('\\', '/'), text_filename: path.relative(root, txt).replaceAll('\\', '/'), content_sha256: sha(bytes), extracted_text_sha256: sha(text), extracted_text_length: text.length, full_document_inspected: text.length > 1000, retrieval_status: 'retrieved_full_document' }
  } catch (error) { return { source_id: source.source_id, title: source.exact_document_title, publisher: source.issuing_organisation, jurisdiction: source.jurisdiction, population: source.population, setting: source.clinical_setting, official_url: source.exact_official_url, retrieval_status: 'blocked_source_access', error: String(error.message ?? error), full_document_inspected: false } }
}
const stop = new Set('the a an and or of to in on for with from by is are was were be as this that only when if not document review reviewed clinician clinical'.split(' '))
const tokens = (v) => new Set(String(v ?? '').toLowerCase().replace(/[^a-z0-9 ]+/g, ' ').split(/\s+/).filter((x) => x.length > 3 && !stop.has(x)))
const overlap = (a, b) => { const x = tokens(a); const y = tokens(b); return x.size && y.size ? [...x].filter((t) => y.has(t)).length / Math.min(x.size, y.size) : 0 }
const normalize = (v) => String(v ?? '').toLowerCase().replace(/\s+/g, ' ').trim()
function makeFamily(key, ids, members) { const first = members[0]; const base = `${first?.specialty ?? 'general'} ${first?.baseline?.clinical_workflow?.diagnosis ?? first?.presentation ?? 'source-gap'}`.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 70); return { family_id: `family-${base || 'source-gap'}-${sha(key).slice(0, 8)}`, family_name: base.replaceAll('-', ' ') || 'source gap', target_population: [...new Set(members.map((m) => m.baseline?.clinical_workflow?.population ?? m.specialty ?? 'general'))].join('; '), intended_setting: [...new Set(members.map((m) => m.baseline?.clinical_workflow?.setting ?? 'clinical documentation'))].join('; '), workflow_ids: members.map((m) => m.workflow_id), source_ids: ids, uae_sources: ids.filter((id) => /UAE|Dubai|Abu Dhabi|Emirates/i.test(sourceMap.get(id)?.jurisdiction ?? '')), international_sources: ids.filter((id) => !/UAE|Dubai|Abu Dhabi|Emirates/i.test(sourceMap.get(id)?.jurisdiction ?? '')), source_hierarchy: 'UAE official sources first, then international governmental or professional guidance with adaptation recorded', applicable_guideline_versions: ids.map((id) => sourceMap.get(id)?.version).filter(Boolean), population_limitations: [...new Set(ids.map((id) => sourceMap.get(id)?.population).filter(Boolean))], setting_limitations: [...new Set(ids.map((id) => sourceMap.get(id)?.clinical_setting).filter(Boolean))], source_conflicts: [], completion_state: 'pending', input_fingerprint: sha(key), output_fingerprint: null } }
async function main() {
  if (workflows.length !== 1500) throw new Error(`Expected 1500 workflows, found ${workflows.length}`)
  const ids = [...sourceMap.keys()].sort(); const archives = []; for (let i = 0; i < ids.length; i += 4) { const chunk = await Promise.all(ids.slice(i, i + 4).map((id) => archive(sourceMap.get(id)))); archives.push(...chunk); process.stdout.write(`\rArchived ${Math.min(i + 4, ids.length)}/${ids.length}`) } process.stdout.write('\n')
  const archiveMap = new Map(archives.map((a) => [a.source_id, a])); const textCache = new Map(archives.filter((a) => a.full_document_inspected).map((a) => [a.source_id, normalize(fs.readFileSync(path.join(root, a.text_filename), 'utf8'))]))
  const groups = new Map(); for (const w of workflows) { const r = research.get(w.workflow_id); const s = [...new Set([...(r?.selected_primary_sources ?? []), ...(r?.selected_supporting_sources ?? [])])].sort(); const key = s.join('|') || `gap|${w.specialty}|${w.baseline?.clinical_workflow?.diagnosis ?? w.presentation}`; if (!groups.has(key)) groups.set(key, []); groups.get(key).push(w) }
  const families = [...groups.entries()].map(([key, members]) => makeFamily(key, [...new Set(key.startsWith('gap|') ? [] : key.split('|'))], members)); const familyIndex = Object.fromEntries(families.map((f) => [f.family_id, f])); const familyFor = new Map(families.flatMap((f) => f.workflow_ids.map((id) => [id, f.family_id])))
  for (const f of families) { const pack = { schema_version: '1.0.0', family_id: f.family_id, sources: f.source_ids.map((id) => ({ ...sourceMap.get(id), archive: archiveMap.get(id) ?? null, exact_relevant_sections: sourceMap.get(id)?.exact_sections ?? [] })), workflow_ids: f.workflow_ids, full_document_inspection: f.source_ids.every((id) => archiveMap.get(id)?.full_document_inspected), source_fingerprints: f.source_ids.map((id) => archiveMap.get(id)?.extracted_text_sha256).filter(Boolean), limitations: f.source_ids.filter((id) => archiveMap.get(id)?.retrieval_status === 'blocked_source_access').map((id) => `${id}: full source unavailable during reconstruction`) }; f.completion_state = pack.full_document_inspection ? 'inspected' : 'blocked_or_gap'; f.output_fingerprint = sha(JSON.stringify(pack)); write(path.join(packRoot, `${f.family_id}.json`), pack); write(path.join(familyRoot, `${f.family_id}.md`), `# ${f.family_name}\n\n- Workflows: ${f.workflow_ids.length}\n- Sources: ${f.source_ids.length}\n- Full documents inspected: ${pack.full_document_inspection ? 'yes' : 'no'}\n- Limitations: ${pack.limitations.length}\n`) }
  write(path.join(exp, 'full-source-reconstruction', 'GUIDELINE_FAMILY_MANIFEST.json'), { schema_version: '1.0.0', generated_on: '2026-07-18', family_count: families.length, families: families.map((f) => ({ ...f, input_fingerprint: f.input_fingerprint, output_fingerprint: f.output_fingerprint })), input_fingerprint: sha(JSON.stringify(workflows.map((w) => w.workflow_id))), output_fingerprint: sha(JSON.stringify(families)) })
  fs.rmSync(outRoot, { recursive: true, force: true }); fs.mkdirSync(path.join(outRoot, 'workflows'), { recursive: true }); const counts = { retained: 0, rewritten: 0, removed: 0, added: 0, comparisons: 0, complete: 0, limitations: 0, gaps: 0, blocked: 0 }; const sectionNames = ['presenting_complaint','focused_history','symptom_onset_duration','symptom_characteristics','associated_symptoms','relevant_negative_symptoms','risk_factors','comorbidities','medication_history','allergy_history','pregnancy_reproductive','red_flags','focused_examination','vital_signs','investigations','testing_thresholds','assessment_structure','differential_diagnostic_framing','non_pharmacological_management','pharmacological_management','escalation_criteria','emergency_referral','routine_referral','follow_up','safety_netting','patient_advice']
  const completed = []; for (const w of workflows) { const r = research.get(w.workflow_id) ?? {}; const sourceIds = [...new Set([...(r.selected_primary_sources ?? []), ...(r.selected_supporting_sources ?? [])])]; const evidence = (r.evidence_items ?? []).filter((e) => archiveMap.get(e.source_id)?.full_document_inspected).map((e, i) => { const s = sourceMap.get(e.source_id); const sec = s?.exact_sections?.find((x) => x.section_id === e.source_section_id); return { workflow_id: w.workflow_id, item_id: `${w.workflow_id}--full-guideline-item--${String(i + 1).padStart(3, '0')}`, section: e.source_section_id, final_wording: e.paraphrased_evidence_summary || e.direct_relationship, action: 'add', source: { source_id: e.source_id, title: s?.exact_document_title ?? null, url: s?.exact_official_url ?? null, jurisdiction: s?.jurisdiction ?? null, population: s?.population ?? null, setting: s?.clinical_setting ?? null, exclusions: s?.applicability_note ?? null, uae_applicability: /UAE|Dubai|Abu Dhabi|Emirates/i.test(s?.jurisdiction ?? ''), exact_location: sec ? { section_id: sec.section_id, heading: sec.heading, locator: sec.locator } : null, evidence_paraphrase: e.paraphrased_evidence_summary || e.direct_relationship, retrieval_date: archiveMap.get(e.source_id)?.accessed_on ?? null, source_fingerprint: archiveMap.get(e.source_id)?.extracted_text_sha256 ?? null }, rationale: e.direct_relationship } })
    const legacy = Object.entries(w.content_sections ?? {}).flatMap(([section, items]) => Array.isArray(items) ? items.map((item) => ({ section, ...item })) : []); const comparisons = legacy.map((item) => { const exact = sourceIds.find((id) => textCache.get(id)?.includes(normalize(item.text))); if (exact) { const e = evidence.find((x) => x.source.source_id === exact); return { previous_item_id: item.item_id, previous_wording: item.text ?? '', action: 'retain', comparison_method: 'full_document_exact_phrase_match', matched_source_id: exact, matched_location: e?.source.exact_location ?? null, reason: 'Exact phrase located in inspected full source.' } } const best = evidence.reduce((b, e) => { const score = overlap(item.text, e.final_wording); return score > (b?.score ?? 0) ? { e, score } : b }, null); return best && best.score >= 0.6 ? { previous_item_id: item.item_id, previous_wording: item.text ?? '', action: 'rewrite', comparison_method: 'full_document_evidence_token_comparison', matched_source_id: best.e.source.source_id, matched_location: best.e.source.exact_location, replacement_wording: best.e.final_wording, scope_difference: 'Rewritten to narrower supported wording.', similarity_score: Number(best.score.toFixed(3)) } : { previous_item_id: item.item_id, previous_wording: item.text ?? '', action: 'remove', comparison_method: sourceIds.length ? 'full_document_no_supporting_match' : 'source_gap_after_full_search', matched_source_id: null, matched_location: null, reason: sourceIds.length ? 'No exact phrase or sufficiently overlapping supported statement in inspected sources.' : 'No authoritative source was identified after the committed research search.' } })
    const retained = comparisons.filter((x) => x.action === 'retain').map((x) => ({ ...evidence.find((e) => e.source.source_id === x.matched_source_id), item_id: x.previous_item_id, action: 'retain', previous_item_id: x.previous_item_id, previous_wording: x.previous_wording, final_wording: x.previous_wording, rationale: x.reason })); const rewritten = comparisons.filter((x) => x.action === 'rewrite').map((x) => ({ ...evidence.find((e) => e.source.source_id === x.matched_source_id), item_id: x.previous_item_id, action: 'rewrite', previous_item_id: x.previous_item_id, previous_wording: x.previous_wording, final_wording: x.replacement_wording, rationale: x.scope_difference })); const removed = comparisons.filter((x) => x.action === 'remove'); const sourceGap = !sourceIds.length; const blocked = sourceIds.some((id) => archiveMap.get(id)?.retrieval_status === 'blocked_source_access'); const status = sourceGap ? 'source_gap_after_full_search' : blocked ? 'blocked_source_access' : 'reconstructed_with_documented_limitations'; const output = { schema_version: '2.0.0', workflow_id: w.workflow_id, workflow_number: w.baseline.source_workflow_index + 1, title: w.presentation, specialty: w.specialty, family_id: familyFor.get(w.workflow_id), status, full_documents_inspected: sourceIds.filter((id) => archiveMap.get(id)?.full_document_inspected), item_level_comparisons: comparisons, items: [...retained, ...rewritten, ...evidence], retained_legacy_items: retained, rewritten_legacy_items: rewritten, removed_legacy_items: removed, added_items: evidence, source_ids: sourceIds, applicable_sections: Object.fromEntries(sectionNames.map((s) => [s, true])), section_omission_reasons: Object.fromEntries(sectionNames.filter((s) => !evidence.some((e) => `${e.section} ${e.final_wording}`.toLowerCase().includes(s.replaceAll('_', ' ')))).map((s) => [s, 'No applicable recommendation located in inspected full-source set; documented limitation.'])), source_gap: sourceGap ? ['No authoritative source after full search.'] : [], limitations: ['Automated source-grounded reconstruction; medication, threshold, referral and safety wording is limited to explicit committed evidence.'] }
    write(path.join(outRoot, 'workflows', `${w.workflow_id}.json`), output); counts.retained += retained.length; counts.rewritten += rewritten.length; counts.removed += removed.length; counts.added += evidence.length; counts.comparisons += comparisons.length; counts[status === 'reconstructed_complete' ? 'complete' : status === 'source_gap_after_full_search' ? 'gaps' : status === 'blocked_source_access' ? 'blocked' : 'limitations']++; completed.push(w.workflow_id)
  }
  const manifest = { schema_version: '2.0.0', workflow_count: 1500, completed_workflow_ids: completed, next_workflow: null, counts, archive_manifest: archives, family_count: families.length, source_gap_workflow_ids: workflows.filter((w) => !research.get(w.workflow_id)?.selected_primary_sources?.length && !research.get(w.workflow_id)?.selected_supporting_sources?.length).map((w) => w.workflow_id), blocked_source_workflow_ids: workflows.filter((w) => [...new Set([...(research.get(w.workflow_id)?.selected_primary_sources ?? []), ...(research.get(w.workflow_id)?.selected_supporting_sources ?? [])])].some((id) => archiveMap.get(id)?.retrieval_status === 'blocked_source_access')).map((w) => w.workflow_id), output_fingerprint: sha(JSON.stringify(completed.map((id) => read(path.join(outRoot, 'workflows', `${id}.json`))))) }; write(path.join(outRoot, 'manifest.json'), manifest); console.log(JSON.stringify({ status: 'PASS', workflows: 1500, families: families.length, full_documents: archives.filter((a) => a.full_document_inspected).length, blocked_sources: archives.filter((a) => a.retrieval_status === 'blocked_source_access').length, ...counts, output_fingerprint: manifest.output_fingerprint }, null, 2))
}
main().catch((e) => { console.error(e.stack ?? e); process.exitCode = 1 })
