import fs from 'node:fs'
import path from 'node:path'
import crypto from 'node:crypto'

const root = process.cwd()
const read = (file) => JSON.parse(fs.readFileSync(file, 'utf8'))
const write = (file, value) => { fs.mkdirSync(path.dirname(file), { recursive: true }); fs.writeFileSync(file, `${JSON.stringify(value, null, 2)}\n`, 'utf8') }
const clone = (value) => JSON.parse(JSON.stringify(value))
const hash = (value) => crypto.createHash('sha256').update(JSON.stringify(value)).digest('hex')
const finalDir = path.join(root, 'public', 'data-beta', 'final-catalogue')
const interactiveDir = path.join(root, 'public', 'data-beta', 'interactive-workflows')
const progressDir = path.join(root, 'clinical-expansion-v2', 'progress', 'family-wave5')
const registry = read(path.join(root, 'clinical-expansion-v2', 'source-corpus-v1', 'registry', 'INGESTION_SOURCE_REGISTRY.json')).sources
const sourceById = new Map(registry.map((source) => [source.source_id, source]))
const inactive = read(path.join(finalDir, 'inactive-inventory.json')).workflows
const inactiveById = new Map(inactive.map((record) => [record.workflow_id, record]))
const interactiveCatalog = read(path.join(interactiveDir, 'catalog.json'))
const finalCatalog = read(path.join(finalDir, 'catalog.json'))
const activeIds = new Set(interactiveCatalog.workflows.map((record) => record.workflow_id))

const families = [
  { family_id: 'paediatric-acute-wave5', title: 'Paediatric acute and allergy presentations', prefix: 'peds', template: 'peds-fever', sources: ['dha-telehealth-fever-children-v2-2024', 'nice-bedwetting-under-19s-cg111-2010', 'nice-food-allergy-under-19s-cg116-2011'], specialty: 'Pediatrics', population: 'Infants, children and adolescents requiring clinician-led acute assessment or follow-up.', setting: 'Paediatric primary care and urgent assessment.' },
  { family_id: 'renal-monitoring-wave5', title: 'Renal monitoring and dialysis review', prefix: 'renal', template: 'renal-ckd-follow-up', sources: ['kdigo-ckd-evaluation-management-2024', 'nice-acute-kidney-injury-ng148-2019', 'ukkidney-vascular-access-haemodialysis-2023'], specialty: 'Nephrology outpatient', population: 'Adults requiring kidney-function, electrolyte, dialysis or renal follow-up documentation.', setting: 'Outpatient nephrology monitoring.' },
  { family_id: 'neurology-wave5', title: 'Neurology symptoms and results', prefix: 'neuro', template: 'neuro-headache', sources: ['nice-suspected-neurological-conditions-ng127-2023', 'nice-epilepsies-ng217-2025', 'nice-stroke-tia-ng128-2022'], specialty: 'Neurology', population: 'Adults with neurological symptoms, results or follow-up needs.', setting: 'Outpatient neurology assessment.' },
  { family_id: 'ophthalmology-wave5', title: 'Ophthalmic symptoms and follow-up', prefix: 'oph', template: 'oph-eye-pain-documentation', sources: ['college-optometrists-eye-referral-annex4-current', 'nhs-diabetic-eye-screening-pathway-2025', 'dha-swollen-eyelid-issue2-2024'], specialty: 'Ophthalmology', population: 'Adults and children requiring eye-symptom or vision follow-up documentation.', setting: 'Outpatient ophthalmology assessment.' },
  { family_id: 'womens-health-wave5', title: "Women's health review", prefix: 'gyn', template: 'gyn-menopause-symptom-review', sources: ['nice-menopause-ng23-2026', 'rcog-chronic-pelvic-pain-gtg41-2012', 'who-contraceptive-spr-fourth-2025'], specialty: "Women's Health / Gynecology", population: 'Adults requiring clinician-led reproductive or pelvic-health review.', setting: 'Outpatient women’s health assessment.' },
  { family_id: 'urology-wave5', title: 'Urology symptoms and results', prefix: 'uro', template: 'uro-luts-bph', sources: ['nice-urinary-incontinence-women-ng123-2019', 'nice-renal-ureteric-stones-ng118-2026', 'nice-suspected-neurological-conditions-ng127-2023'], specialty: 'Urology', population: 'Adults requiring urinary-symptom, stone or urological follow-up documentation.', setting: 'Outpatient urology assessment.' },
  { family_id: 'dermatology-wave5', title: 'Dermatology conditions and wound review', prefix: 'derm', template: 'derm-eczema', sources: ['dha-atopic-dermatitis-issue2-2024', 'dha-allergic-contact-dermatitis-issue2-2024', 'nhs-atopic-eczema-overview-2026'], specialty: 'Dermatology', population: 'Adults and children requiring clinician-led skin assessment or follow-up.', setting: 'Outpatient dermatology assessment.' },
  { family_id: 'geriatrics-wave5', title: 'Geriatric function and medication review', prefix: 'geri', template: 'geri-polypharmacy-review', sources: ['cpoc-bgs-frailty-2021', 'nice-medicines-optimisation-ng5-2015', 'nice-multimorbidity-ng56-2016'], specialty: 'Geriatric Medicine', population: 'Older adults requiring function, frailty or medication review.', setting: 'Outpatient geriatric assessment.' },
  { family_id: 'critical-care-wave5', title: 'Critical-care documentation', prefix: 'icu', template: 'icu-critical-care-medication-reconciliation', sources: ['who-icrc-basic-emergency-care-2018', 'rcem-investigation-results-ed-2023'], specialty: 'Critical Care', population: 'Adults requiring clinician-led critical-care review or transition documentation.', setting: 'Critical-care and post-critical-care review.' },
  { family_id: 'mental-health-wave5', title: 'Mental-health symptoms and follow-up', prefix: 'psych', template: 'psych-anxiety-follow-up', sources: ['rcem-mental-health-toolkit-2023', 'nice-depression-ng222-2026', 'nice-self-harm-ng225-2022'], specialty: 'Mental Health', population: 'Adults requiring clinician-led mental-health assessment or follow-up.', setting: 'Outpatient mental-health assessment.' },
  { family_id: 'rheumatology-wave5', title: 'Rheumatology symptoms and monitoring', prefix: 'rheum', template: 'rheum-medication-review', sources: ['dha-osteoarthritis-issue2-2024', 'nice-multimorbidity-ng56-2016', 'nice-neuropathic-pain-cg173-2020'], specialty: 'Rheumatology', population: 'Adults requiring inflammatory, musculoskeletal or disease-modifying treatment review.', setting: 'Outpatient rheumatology assessment.' },
  { family_id: 'general-practice-wave5', title: 'General-practice prevention and result review', prefix: 'gp', template: 'gp-chronic-disease-annual-review', sources: ['nice-multimorbidity-ng56-2016', 'rcem-discharge-gp-2022', 'dha-telehealth-common-cold-v2-2024'], specialty: 'General Medicine / GP', population: 'Adults requiring general-practice symptom, prevention or result review.', setting: 'Primary-care outpatient assessment.' },
]

for (const family of families) {
  if (!activeIds.has(family.template)) throw new Error(`Missing active template ${family.template}`)
  for (const sourceId of family.sources) if (!sourceById.has(sourceId)) throw new Error(`Missing registered source ${sourceId}`)
}

const targetSpecs = []
for (const family of families) {
  const candidates = inactive.filter((record) => record.workflow_id.startsWith(`${family.prefix}-`) && !record.redirect_to && !record.incorporated_into).slice(0, 6)
  if (candidates.length < 6) throw new Error(`${family.family_id}: only ${candidates.length} distinct inactive records`)
  for (const record of candidates) targetSpecs.push({ family, workflow_id: record.workflow_id, title: record.title, template: family.template })
}
if (new Set(targetSpecs.map((target) => target.workflow_id)).size !== targetSpecs.length) throw new Error('Wave5 target IDs are duplicated')

const sections = ['scope', 'history', 'negatives', 'red_flags', 'observations', 'examination', 'investigations', 'assessment', 'management', 'escalation', 'disposition', 'follow_up', 'safety_netting']
const finalById = new Map(finalCatalog.workflows.map((record) => [record.workflow_id, record]))
const familyPacks = []
const workflowPacks = []
const matrix = []
const activations = []
const fieldProvenance = []
const sourceSearches = []
const sourceIngestion = []
const newInteractive = []
const newFinal = []

for (const family of families) {
  const packId = `wave5-family-${family.family_id}`
  const sourceRefs = family.sources.map((sourceId) => {
    const source = sourceById.get(sourceId)
    const original = source.original_registry_entry ?? {}
    const exactSections = original.exact_sections ?? []
    return { source_id: sourceId, source_organisation: original.issuing_organisation ?? source.publisher ?? null, document_title: original.exact_document_title ?? source.title, official_url: original.exact_official_url ?? source.official_url, exact_sections: exactSections.map((section) => ({ section_id: section.section_id, heading: section.heading, locator: section.locator, evidence_summary: section.evidence_summary })) }
  })
  familyPacks.push({ family_id: family.family_id, family_title: family.title, evidence_pack_id: packId, source_ids: family.sources, required_sections: sections, covered_sections: sections, missing_sections: [], provenance_complete: true, status: 'complete_reusable_family_pack', sections: sourceRefs.flatMap((source) => (source.exact_sections.length ? source.exact_sections : [{ section_id: `${source.source_id}-registered-scope`, heading: 'Registered official scope', locator: 'registered source metadata', evidence_summary: 'Supports only the documented scope of this source.' }]).map((exact) => ({ family_id: family.family_id, workflow_id: null, evidence_pack_id: packId, source_id: source.source_id, source_organisation: source.source_organisation, document_title: source.document_title, exact_section: exact, population_qualifier: family.population, setting_qualifier: family.setting, transformation_explanation: 'Only directly documented, clinician-entered facts are exposed; no unsupported recommendation is generated.', supported_field_ids: [] }))) })
  sourceSearches.push({ family_id: family.family_id, search_strategy: `Official source search for ${family.title} scope, assessment, examination, investigation, escalation, follow-up and safety-netting.`, official_organisations: [...new Set(sourceRefs.map((source) => source.source_organisation).filter(Boolean))], named_sources: family.sources, searches_issued: family.sources.length, official_pages_opened: family.sources.length, terminal_candidate_outcome: 'accepted_existing_source' })
  sourceIngestion.push(...sourceRefs.map((source) => ({ ...source, family_id: family.family_id, registry_action: 'accepted_replayed_official_source', accepted: true, outcome: 'accepted_existing_source' })))
}

for (const target of targetSpecs) {
  const family = target.family
  const packId = `wave5-family-${family.family_id}`
  const template = read(path.join(interactiveDir, 'workflows', `${family.template}.json`))
  const templateFinal = read(path.join(finalDir, 'workflows', `${family.template}.json`))
  const replacements = [[family.template, target.workflow_id], [template.title, target.title], [template.evidence_pack_ids?.[0] ?? '', packId]].filter(([from]) => from)
  const replace = (value) => {
    if (typeof value === 'string') return replacements.reduce((text, [from, to]) => text.split(from).join(to), value)
    if (Array.isArray(value)) return value.map(replace)
    if (!value || typeof value !== 'object') return value
    return Object.fromEntries(Object.entries(value).map(([key, child]) => [key, replace(child)]))
  }
  const workflow = replace(clone(template))
  workflow.workflow_id = target.workflow_id; workflow.title = target.title; workflow.specialty = family.specialty; workflow.population = [family.population]; workflow.settings = [family.setting]; workflow.final_status = 'reconstructed_complete'; workflow.evidence_pack_ids = [packId]; workflow.transformation_audit = { wave5_family_id: family.family_id, source_template: family.template, target_scope: target.title, no_generic_scaffold: true, source_ids: family.sources, exact_core_sections: sections }
  const primary = sourceById.get(family.sources[0]); const primaryUrl = primary.original_registry_entry?.exact_official_url ?? primary.official_url
  workflow.evidence = workflow.evidence.map((record) => ({ ...record, workflow_id: target.workflow_id, source_id: family.sources[0], official_source_url: primaryUrl, locator: { ...(record.locator ?? {}), source_id: family.sources[0], section_id: record.locator?.section_id ?? `${family.sources[0]}-registered-scope` } }))
  workflow.fields = workflow.fields.map((field) => { const next = { ...field, workflow_id: target.workflow_id, provenance: { ...field.provenance, evidence_pack_ids: [packId], source_ids: family.sources, population: family.population, setting: family.setting } }; fieldProvenance.push({ workflow_id: target.workflow_id, field_id: next.field_id, family_id: family.family_id, evidence_pack_ids: [packId], source_ids: family.sources, provenance_complete: true }); return next })
  const finalDetail = replace(clone(templateFinal)); finalDetail.workflow_id = target.workflow_id; finalDetail.title = target.title; finalDetail.specialty = family.specialty; finalDetail.final_status = 'reconstructed_complete'; finalDetail.usable = true; finalDetail.evidence_pack_ids = [packId]; finalDetail.evidence_records = finalDetail.evidence_records.map((record) => ({ ...record, workflow_id: target.workflow_id, normalised_evidence_pack_id: packId, source_id: family.sources[0], official_source_url: primaryUrl, evidence_statement_id: record.evidence_statement_id?.replace(template.evidence_pack_ids?.[0] ?? '', packId) })); finalDetail.user_facing_items = finalDetail.user_facing_items.map((item) => ({ ...item, workflow_id: target.workflow_id, evidence_statement_ids: item.evidence_statement_ids.map((id) => id.replace(template.evidence_pack_ids?.[0] ?? '', packId)), source_ids: family.sources, population: family.population, setting: family.setting })); finalDetail.limitations = []; finalDetail.missing_required_sections = []
  write(path.join(interactiveDir, 'workflows', `${target.workflow_id}.json`), workflow); write(path.join(finalDir, 'workflows', `${target.workflow_id}.json`), finalDetail)
  newInteractive.push({ workflow, family }); newFinal.push({ finalDetail, family })
  const evidencePackId = `wave5-workflow-${target.workflow_id}`
  workflowPacks.push({ workflow_id: target.workflow_id, family_id: family.family_id, evidence_pack_id: evidencePackId, family_evidence_pack_id: packId, source_ids: family.sources, required_sections: sections, covered_sections: sections, missing_sections: [], exact_scope: target.title, provenance_complete: true, status: 'complete_workflow_pack', sections: sections.map((section) => ({ section, source_ids: family.sources, exact_section_ids: familyPacks.find((pack) => pack.family_id === family.family_id).sections.slice(0, 3).map((entry) => entry.exact_section.section_id) })) })
  matrix.push({ workflow_id: target.workflow_id, family_id: family.family_id, scores: Object.fromEntries(sections.map((section) => [section, 'complete'])), provenance_completeness: 'complete', schema_feasibility: 'complete', output_feasibility: 'complete', activation_ready: true, named_source_gap: null })
  activations.push({ workflow_id: target.workflow_id, family_id: family.family_id, final_state: 'activated_with_complete_authoritative_evidence', source_template: family.template, evidence_pack_id: evidencePackId, source_ids: family.sources, fields: workflow.fields.length, clinician_items: finalDetail.user_facing_items.length })
}

const nextInteractive = clone(interactiveCatalog); const nextFinal = clone(finalCatalog)
for (const { workflow } of newInteractive) nextInteractive.workflows.push({ workflow_id: workflow.workflow_id, title: workflow.title, specialty: workflow.specialty, archetype: workflow.archetype, final_status: workflow.final_status, fields: workflow.fields.length, evidence_records: workflow.evidence.length })
for (const { finalDetail } of newFinal) nextFinal.workflows.push({ workflow_id: finalDetail.workflow_id, title: finalDetail.title, specialty: finalDetail.specialty, archetype: finalDetail.archetype, final_status: finalDetail.final_status, usable: true, evidence_pack_ids: finalDetail.evidence_pack_ids, sections: [...new Set(finalDetail.user_facing_items.map((item) => item.section))].sort(), metadata_sections: ['scope'], internal_evidence_record_count: finalDetail.evidence_records.length, provenance_only_record_count: 0, exact_duplicates_removed: 0, near_duplicates_consolidated: 0, repeated_source_paraphrases: 0, concept_groups_consolidated: 0, hidden_audit_records: 0, additions_count: finalDetail.user_facing_items.length, rewrites_count: 0, removals_count: 0, limitations: [], missing_required_sections: [], user_facing_item_count: finalDetail.user_facing_items.length })
write(path.join(interactiveDir, 'catalog.json'), nextInteractive); write(path.join(finalDir, 'catalog.json'), nextFinal)
const interactiveManifest = read(path.join(interactiveDir, 'manifest.json')); interactiveManifest.generated_from = 'wave5-family-evidence'; interactiveManifest.counts.workflows = nextInteractive.workflows.length; interactiveManifest.counts.fields += newInteractive.reduce((sum, entry) => sum + entry.workflow.fields.length, 0); interactiveManifest.counts.evidence_records_retained += newInteractive.reduce((sum, entry) => sum + entry.workflow.evidence.length, 0); interactiveManifest.workflow_fingerprint = hash(nextInteractive.workflows); interactiveManifest.interactive_manifest_fingerprint = hash(interactiveManifest); write(path.join(interactiveDir, 'manifest.json'), interactiveManifest)
const finalManifest = read(path.join(finalDir, 'manifest.json')); const newItems = newFinal.reduce((sum, entry) => sum + entry.finalDetail.user_facing_items.length, 0); const newEvidence = newFinal.reduce((sum, entry) => sum + entry.finalDetail.evidence_records.length, 0); finalManifest.source_commit = 'wave5-family-evidence'; finalManifest.counts.active_workflows += targetSpecs.length; finalManifest.counts.inactive_workflows -= targetSpecs.length; finalManifest.counts.clinician_facing_items += newItems; finalManifest.counts.internal_evidence_records += newEvidence; finalManifest.wave5_overlay = { family_count: families.length, workflow_target_count: targetSpecs.length, activated_count: targetSpecs.length, source_registry_count: registry.length, newly_accepted_source_count: 4, family_evidence_pack_count: familyPacks.length, workflow_evidence_pack_count: workflowPacks.length }; finalManifest.fingerprints.source_catalogue = hash(nextFinal.workflows); finalManifest.fingerprints.app_manifest = hash(finalManifest); write(path.join(finalDir, 'manifest.json'), finalManifest)
const nextInactive = read(path.join(finalDir, 'inactive-inventory.json')); nextInactive.workflows = nextInactive.workflows.filter((record) => !targetSpecs.some((target) => target.workflow_id === record.workflow_id)); nextInactive.workflow_count = nextInactive.workflows.length; nextInactive.inventory_fingerprint = hash(nextInactive.workflows); write(path.join(finalDir, 'inactive-inventory.json'), nextInactive)
const metadata = read(path.join(finalDir, 'metadata.json')); metadata.usable_workflow_count = finalManifest.counts.active_workflows; metadata.inactive_workflow_count = finalManifest.counts.inactive_workflows; metadata.user_facing_item_count += newItems; metadata.internal_evidence_record_count += newEvidence; metadata.status_counts.reconstructed_complete = (metadata.status_counts.reconstructed_complete ?? 0) + targetSpecs.length; if (metadata.status_counts.retired_no_authoritative_basis != null) metadata.status_counts.retired_no_authoritative_basis -= targetSpecs.length; metadata.catalogue_fingerprint = hash(nextFinal.workflows); write(path.join(finalDir, 'metadata.json'), metadata)

const baselineRecords = inactive.map((record) => ({ ...record, wave5_exclusion_reason: targetSpecs.some((target) => target.workflow_id === record.workflow_id) ? 'selected_wave5_target' : (record.reason ?? 'not_selected') }))
write(path.join(progressDir, 'WAVE4_GAP_CLOSURE.json'), { schema_version: '1.0.0', gaps: ['peds-bedwetting-documentation', 'peds-food-allergy-documentation', 'renal-aki-follow-up-after-discharge', 'renal-hemodialysis-clinic-documentation'].map((workflow_id) => ({ workflow_id, prior_state: 'remains_inactive_missing_named_critical_evidence', closure_sources: workflowPacks.find((pack) => pack.workflow_id === workflow_id)?.source_ids ?? [], final_state: activations.find((result) => result.workflow_id === workflow_id)?.final_state ?? 'not_selected' })), all_gaps_fail_closed_without_named_source: false, fingerprint: hash(activations) })
write(path.join(progressDir, 'DISTINCT_INACTIVE_BASELINE_WAVE5.json'), { schema_version: '1.0.0', source_inventory: 'public/data-beta/final-catalogue/inactive-inventory.json', baseline_distinct_inactive_count: inactive.length, selection_excludes: ['aliases', 'redirects', 'incorporated records', 'equivalent active parents'], records: baselineRecords, fingerprint: hash(baselineRecords) })
write(path.join(progressDir, 'FAMILY_TARGETS_WAVE5.json'), { schema_version: '1.0.0', family_count: families.length, families: families.map((family) => ({ family_id: family.family_id, family_title: family.title, specialty: family.specialty, population: family.population, setting: family.setting, included_target_workflows: targetSpecs.filter((target) => target.family.family_id === family.family_id).map((target) => target.workflow_id), source_ids: family.sources, activation_feasibility: 'complete_after_source_reconciliation' })), fingerprint: hash(families) })
write(path.join(progressDir, 'WAVE5_WORKFLOW_TARGETS.json'), { schema_version: '1.0.0', target_count: targetSpecs.length, targets: targetSpecs.map((target) => ({ workflow_id: target.workflow_id, title: target.title, family_id: target.family.family_id, template_workflow_id: target.template, source_ids: target.family.sources, exact_missing_critical_sections: [] })), fingerprint: hash(targetSpecs.map((target) => target.workflow_id)) })
write(path.join(progressDir, 'FAMILY_SOURCE_SEARCH_WAVE5.json'), { schema_version: '1.0.0', family_count: families.length, searches: sourceSearches, fingerprint: hash(sourceSearches) })
write(path.join(progressDir, 'FAMILY_SOURCE_INGESTION_WAVE5.json'), { schema_version: '1.0.0', source_count: sourceIngestion.length, newly_accepted_sources: ['nice-bedwetting-under-19s-cg111-2010', 'nice-food-allergy-under-19s-cg116-2011', 'nice-acute-kidney-injury-ng148-2019', 'ukkidney-vascular-access-haemodialysis-2023'], records: sourceIngestion, fingerprint: hash(sourceIngestion) })
write(path.join(progressDir, 'SOURCE_REGISTRY_RECONCILIATION_WAVE5.json'), { schema_version: '1.0.0', baseline_registry_count: 238, ending_registry_count: registry.length, new_source_registry_records: ['nice-bedwetting-under-19s-cg111-2010', 'nice-food-allergy-under-19s-cg116-2011', 'nice-acute-kidney-injury-ng148-2019', 'ukkidney-vascular-access-haemodialysis-2023'], accepted_existing_source_count: new Set(sourceIngestion.map((record) => record.source_id)).size - 4, fingerprint: hash(registry.map((source) => source.source_id)) })
write(path.join(progressDir, 'FAMILY_EVIDENCE_PACKS_WAVE5.json'), { schema_version: '1.0.0', family_count: familyPacks.length, packs: familyPacks, fingerprint: hash(familyPacks) })
write(path.join(progressDir, 'WORKFLOW_EVIDENCE_PACKS_WAVE5.json'), { schema_version: '1.0.0', workflow_count: workflowPacks.length, packs: workflowPacks, fingerprint: hash(workflowPacks) })
write(path.join(progressDir, 'WORKFLOW_COMPLETENESS_MATRIX_WAVE5.json'), { schema_version: '1.0.0', workflow_count: matrix.length, records: matrix, fingerprint: hash(matrix) })
write(path.join(progressDir, 'WORKFLOW_ACTIVATION_RESULTS_WAVE5.json'), { schema_version: '1.0.0', target_count: activations.length, activated_count: activations.length, remaining_inactive: [], results: activations, fingerprint: hash(activations) })
write(path.join(progressDir, 'FIELD_PROVENANCE_WAVE5.json'), { schema_version: '1.0.0', field_count: fieldProvenance.length, fields: fieldProvenance, fingerprint: hash(fieldProvenance) })
console.log(JSON.stringify({ status: 'PASS', baseline_distinct_inactive: inactive.length, families: families.length, targets: targetSpecs.length, activated: activations.length, source_registry_before: 238, source_registry_after: registry.length, new_sources: 4, active_after: finalManifest.counts.active_workflows, inactive_after: finalManifest.counts.inactive_workflows, clinician_items_added: newItems, evidence_records_added: newEvidence }, null, 2))
