/* oxlint-disable no-unused-expressions */
async page => {
  const base = 'https://hosxam.github.io/najm-ai-clinicnote-v2-beta'; const bust = Date.now(); const consoleErrors = []; const failedRequests = []
  page.on('console', message => { if (message.type() === 'error') consoleErrors.push(message.text()) }); page.on('requestfailed', request => { const reason = request.failure()?.errorText ?? 'failed'; if (!/ABORTED/i.test(reason)) failedRequests.push(`${request.url()} :: ${reason}`) })
  const manifests = await page.evaluate(async ({ base, bust }) => ({ final: await fetch(`${base}/data-beta/final-catalogue/manifest.json?wave7=${bust}`).then(r => r.json()), interactive: await fetch(`${base}/data-beta/interactive-workflows/manifest.json?wave7=${bust}`).then(r => r.json()) }), { base, bust })
  await page.goto(`${base}/?wave7=${bust}#/beta`); await page.waitForLoadState('networkidle'); await page.evaluate(() => localStorage.clear()); await page.reload(); await page.waitForLoadState('networkidle')
  const homeLoaded = await page.getByRole('textbox', { name: 'Search interactive workflows' }).count() === 1; const body = await page.locator('body').innerText(); const buildText = body.match(/(?:build|version|commit)[^\n]*([0-9a-f]{7,40})/i)?.[1] ?? ''
  const routeIds = ['gp-breast-pain', 'msk-acute-sprain', 'derm-cherry-angioma', 'ed-headache-documentation', 'peds-rash', 'anes-airway-review-documentation', 'uro-hematuria', 'psych-grief-and-bereavement-review', 'endo-prediabetes-review', 'icu-family-meeting-documentation']
  const routes = []; for (const id of routeIds) { await page.goto(`${base}/?wave7=${bust}-${id}#/beta/workflows/${id}`); await page.waitForLoadState('networkidle'); const text = await page.locator('body').innerText(); routes.push({ id, quick: await page.getByRole('button', { name: 'Quick', exact: true }).count() === 1, advanced: await page.getByRole('button', { name: 'Advanced', exact: true }).count() === 1, differentiated: /specific|workflow-specific|Wave-7/i.test(text) }) }
  const inactiveId = JSON.parse(await page.evaluate(async ({ base, bust }) => fetch(`${base}/data-beta/final-catalogue/inactive-inventory.json?wave7=${bust}`).then(r => r.text()), { base, bust })).workflows[0]?.workflow_id; let inactiveIsolation = { id: inactiveId, usable: true }; if (inactiveId) { await page.goto(`${base}/?wave7=${bust}-inactive#/beta/workflows/${inactiveId}`); await page.waitForLoadState('networkidle'); inactiveIsolation = { id: inactiveId, usable: await page.getByRole('button', { name: 'Quick', exact: true }).count() > 0 } }
  const viewports = []; for (const [name, width, height] of [['desktop', 1440, 900], ['tablet', 1024, 768], ['mobile', 390, 844]]) { await page.setViewportSize({ width, height }); await page.goto(`${base}/?wave7=${bust}-${name}#/beta`); await page.waitForLoadState('networkidle'); viewports.push({ name, loaded: await page.getByRole('textbox', { name: 'Search interactive workflows' }).count() === 1, overflow: await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth + 1) }) }
  const counts = manifests.final.counts ?? {}; const pass = counts.original_workflows === 1500 && counts.active_workflows === 741 && counts.inactive_workflows === 759 && counts.clinician_facing_items === 12176 && counts.internal_evidence_records === 131881 && homeLoaded && routes.every(route => route.quick && route.advanced && route.differentiated) && !inactiveIsolation.usable && viewports.every(view => view.loaded && !view.overflow) && consoleErrors.length === 0 && failedRequests.length === 0
  return { status: pass ? 'PASS' : 'FAIL', build_text: buildText, home_loaded: homeLoaded, manifest_counts: counts, interactive_counts: manifests.interactive.counts ?? {}, routes, inactive_isolation: inactiveIsolation, viewports, console_errors: consoleErrors, failed_requests: failedRequests }
}
