async page => {
  const base = 'https://hosxam.github.io/najm-ai-clinicnote-v2-beta'
  const cache = `?wave5=${Date.now()}`
  const consoleErrors = []; const failedRequests = []
  page.on('console', message => { if (message.type() === 'error') consoleErrors.push(message.text()) })
  page.on('requestfailed', request => failedRequests.push(`${request.url()} :: ${request.failure()?.errorText ?? 'failed'}`))
  const manifests = await page.evaluate(async url => { const manifest = await fetch(`${url}/data-beta/final-catalogue/manifest.json`).then(r => r.json()); const interactive = await fetch(`${url}/data-beta/interactive-workflows/manifest.json`).then(r => r.json()); return { manifest, interactive } }, base)
  const expected = { original: 1500, active: 531, inactive: 969, items: 8165, evidence: 83332, fields: 5785 }
  const manifestPass = manifests.manifest.counts.original_workflows === expected.original && manifests.manifest.counts.active_workflows === expected.active && manifests.manifest.counts.inactive_workflows === expected.inactive && manifests.manifest.counts.clinician_facing_items === expected.items && manifests.manifest.counts.internal_evidence_records === expected.evidence && manifests.interactive.counts.workflows === expected.active && manifests.interactive.counts.fields === expected.fields
  await page.goto(`${base}/${cache}#/beta`); await page.waitForLoadState('networkidle')
  const catalogueText = await page.locator('body').innerText(); const catalogueLoaded = await page.getByRole('textbox', { name: 'Search interactive workflows' }).count() === 1 && /531|8165|8,165/.test(catalogueText)
  const ids = ['peds-bedwetting-documentation','peds-food-allergy-documentation','renal-aki-follow-up-after-discharge','renal-hemodialysis-clinic-documentation','neuro-balance-problem-documentation','oph-adult-strabismus-follow-up','gyn-abnormal-uterine-bleeding','uro-balanitis-follow-up','derm-abscess-wound-check','geri-activities-of-daily-living-documentation','icu-agitation-documentation','psych-adhd-follow-up']
  const routes = []
  for (const id of ids) { await page.goto(`${base}/${cache}#/beta/workflows/${id}`); await page.waitForLoadState('networkidle'); const title = (await page.locator('h1').first().textContent().catch(() => ''))?.trim() ?? ''; const quick = await page.getByRole('button', { name: 'Quick', exact: true }).count() === 1; const advanced = await page.getByRole('button', { name: 'Advanced', exact: true }).count() === 1; if (advanced) await page.getByRole('button', { name: 'Advanced', exact: true }).click(); await page.waitForTimeout(50); const advancedRendered = await page.getByText('All supported source-grounded fields in schema order.').count() === 1 || await page.locator('body').innerText().then(t => t.includes('Advanced')); routes.push({ workflow_id: id, title, quick, advanced, advanced_rendered: advancedRendered }) }
  const viewports = []; for (const [name,width,height] of [['desktop',1440,900],['tablet',1024,768],['mobile',390,844]]) { await page.setViewportSize({ width, height }); await page.goto(`${base}/${cache}#/beta`); await page.waitForLoadState('domcontentloaded'); viewports.push({ viewport: name, loaded: await page.getByRole('textbox', { name: 'Search interactive workflows' }).count() === 1, overflow: await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth + 1) }) }
  return { status: manifestPass && catalogueLoaded && routes.every(route => route.quick && route.advanced && route.advanced_rendered) && viewports.every(view => view.loaded && !view.overflow) && consoleErrors.length === 0 && failedRequests.length === 0 ? 'PASS' : 'FAIL', deployed_sha: manifests.manifest.source_commit, manifests, expected, manifest_pass: manifestPass, catalogue_loaded: catalogueLoaded, routes, viewports, console_errors: consoleErrors, failed_requests: failedRequests }
}
