import fs from 'node:fs'
import path from 'node:path'
const root = process.cwd(); const p = path.join(root, 'clinical-expansion-v2/progress/family-wave7'); const beta = path.join(root, 'public/data-beta'); const read = f => JSON.parse(fs.readFileSync(f, 'utf8')); const errors = []
const baseline = read(path.join(p, 'DISTINCT_INACTIVE_BASELINE_WAVE7.json')); const families = read(path.join(p, 'FAMILY_TARGETS_WAVE7.json')); const targets = read(path.join(p, 'WAVE7_WORKFLOW_TARGETS.json')); const activation = read(path.join(p, 'WORKFLOW_ACTIVATION_RESULTS_WAVE7.json')); const packs = read(path.join(p, 'WORKFLOW_EVIDENCE_PACKS_WAVE7.json')); const matrix = read(path.join(p, 'WORKFLOW_COMPLETENESS_MATRIX_WAVE7.json')); const diff = read(path.join(p, 'SCHEMA_DIFFERENTIATION_MATRIX_WAVE7.json')); const provenance = read(path.join(p, 'FIELD_PROVENANCE_WAVE7.json')); const adversarial = read(path.join(p, 'WAVE6_ADVERSARIAL_RESULTS.json')); const manifest = read(path.join(beta, 'final-catalogue/manifest.json')); const catalog = read(path.join(beta, 'final-catalogue/catalog.json')); const inactive = read(path.join(beta, 'final-catalogue/inactive-inventory.json'))
if (baseline.baseline_inactive_count !== 879 || baseline.records.length !== 879) errors.push('inactive baseline does not equal current 879')
if (families.family_count !== 18 || families.families.length !== 18) errors.push('family count does not equal 18')
if (targets.target_count !== 130 || targets.targets.length !== 130) errors.push('target count does not equal 130')
if (new Set(targets.targets.map(row => row.workflow_id)).size !== 130) errors.push('duplicate target IDs')
if (activation.target_count !== 130 || activation.activated_count !== 120 || activation.results.length !== 130) errors.push('activation totals do not reconcile')
if (packs.workflow_count !== 130 || matrix.workflow_count !== 130 || diff.workflow_count !== 130) errors.push('workflow artifact totals do not reconcile')
if (adversarial.fixture_count !== 30 || adversarial.passed !== 30 || adversarial.status !== 'PASS') errors.push('Wave6 adversarial proof incomplete')
if (manifest.counts.original_workflows !== 1500 || manifest.counts.active_workflows !== 741 || manifest.counts.inactive_workflows !== 759) errors.push('catalogue counts do not match Wave7 result')
if (catalog.workflows.length !== 741 || inactive.workflows.length !== 759) errors.push('active/inactive catalogue counts do not match')
for (const row of targets.targets) { const result = activation.results.find(item => item.workflow_id === row.workflow_id); if (!result) errors.push(`${row.workflow_id}: missing terminal state`); if (result?.final_state === 'activated_with_complete_authoritative_evidence' && !fs.existsSync(path.join(beta, 'interactive-workflows/workflows', `${row.workflow_id}.json`))) errors.push(`${row.workflow_id}: activated detail missing`) }
if (provenance.field_count !== 390 || provenance.fields.some(field => !field.workflow_id || !field.field_id || !field.evidence_pack_ids?.length || !field.source_ids?.length || !field.exact_section || !field.population_qualifier || !field.setting_qualifier)) errors.push('field provenance incomplete')
console.log(JSON.stringify({ status: errors.length ? 'FAIL' : 'PASS', baseline: baseline.records.length, families: families.family_count, targets: targets.target_count, activated: activation.activated_count, remaining_inactive: activation.remaining_inactive.length, active_workflows: manifest.counts.active_workflows, inactive_workflows: manifest.counts.inactive_workflows, fields_added: provenance.field_count, adversarial: `${adversarial.passed}/${adversarial.fixture_count}`, errors }, null, 2)); if (errors.length) process.exitCode = 1
