import fs from 'node:fs'
import path from 'node:path'
const root = process.cwd(); const read = (file) => JSON.parse(fs.readFileSync(file, 'utf8')); const errors = []
const progress = path.join(root, 'clinical-expansion-v2/progress/family-wave5'); const finalDir = path.join(root, 'public/data-beta/final-catalogue'); const interactiveDir = path.join(root, 'public/data-beta/interactive-workflows')
const baseline = read(path.join(progress, 'DISTINCT_INACTIVE_BASELINE_WAVE5.json')); const families = read(path.join(progress, 'FAMILY_TARGETS_WAVE5.json')); const targets = read(path.join(progress, 'WAVE5_WORKFLOW_TARGETS.json')); const closure = read(path.join(progress, 'WAVE4_GAP_CLOSURE.json')); const registry = read(path.join(progress, 'SOURCE_REGISTRY_RECONCILIATION_WAVE5.json')); const sourceIngestion = read(path.join(progress, 'FAMILY_SOURCE_INGESTION_WAVE5.json')); const familyPacks = read(path.join(progress, 'FAMILY_EVIDENCE_PACKS_WAVE5.json')); const workflowPacks = read(path.join(progress, 'WORKFLOW_EVIDENCE_PACKS_WAVE5.json')); const matrix = read(path.join(progress, 'WORKFLOW_COMPLETENESS_MATRIX_WAVE5.json')); const activation = read(path.join(progress, 'WORKFLOW_ACTIVATION_RESULTS_WAVE5.json')); const manifest = read(path.join(finalDir, 'manifest.json')); const catalog = read(path.join(finalDir, 'catalog.json')); const inactive = read(path.join(finalDir, 'inactive-inventory.json')); const interactiveManifest = read(path.join(interactiveDir, 'manifest.json')); const interactiveCatalog = read(path.join(interactiveDir, 'catalog.json'))
if (baseline.baseline_distinct_inactive_count !== 1043) errors.push(`baseline count ${baseline.baseline_distinct_inactive_count} != 1043`)
if (families.family_count !== 12 || families.families.length !== 12) errors.push('family count is not 12')
if (targets.target_count < 60 || targets.target_count > 80 || targets.targets.length !== targets.target_count) errors.push('target count outside 60-80 or inconsistent')
if (new Set(targets.targets.map((target) => target.workflow_id)).size !== targets.target_count) errors.push('duplicate target IDs')
if (workflowPacks.workflow_count !== targets.target_count || matrix.workflow_count !== targets.target_count || activation.target_count !== targets.target_count || activation.activated_count !== targets.target_count) errors.push('target artifact counts disagree')
if (familyPacks.family_count !== 12 || familyPacks.packs.some((pack) => !pack.provenance_complete || !pack.sections?.length)) errors.push('family evidence pack is incomplete')
if (workflowPacks.packs.some((pack) => !pack.provenance_complete || !pack.sections?.length)) errors.push('workflow evidence pack is incomplete')
if (registry.baseline_registry_count !== 238 || registry.ending_registry_count !== 242 || registry.new_source_registry_records.length !== 4) errors.push('source registry reconciliation is invalid')
if (sourceIngestion.newly_accepted_sources.length !== 4 || sourceIngestion.records.some((record) => record.outcome !== 'accepted_existing_source')) errors.push('source ingestion has non-terminal or missing records')
for (const gap of ['peds-bedwetting-documentation','peds-food-allergy-documentation','renal-aki-follow-up-after-discharge','renal-hemodialysis-clinic-documentation']) { const result = activation.results.find((entry) => entry.workflow_id === gap); if (!result || result.final_state !== 'activated_with_complete_authoritative_evidence') errors.push(`${gap} gap not closed with activation`) }
const activeIds = new Set(catalog.workflows.map((workflow) => workflow.workflow_id)); const inactiveIds = new Set(inactive.workflows.map((workflow) => workflow.workflow_id))
for (const target of targets.targets) { if (!activeIds.has(target.workflow_id) || inactiveIds.has(target.workflow_id)) errors.push(`${target.workflow_id} is not active-only`); const workflowFile = path.join(interactiveDir, 'workflows', `${target.workflow_id}.json`); const finalFile = path.join(finalDir, 'workflows', `${target.workflow_id}.json`); if (!fs.existsSync(workflowFile) || !fs.existsSync(finalFile)) errors.push(`${target.workflow_id} detail file missing`); else { const workflow = read(workflowFile); const evidence = new Set(workflow.evidence.map((record) => record.evidence_statement_id)); if (workflow.evidence.some((record) => !record.source_id || !record.official_source_url || !record.locator?.section_id)) errors.push(`${target.workflow_id} evidence provenance incomplete`); if (workflow.fields.some((field) => !field.provenance?.evidence_statement_ids?.length || field.provenance.evidence_statement_ids.some((id) => !evidence.has(id)))) errors.push(`${target.workflow_id} field provenance incomplete`) } }
if (manifest.counts.original_workflows !== 1500 || manifest.counts.active_workflows !== catalog.workflows.length || manifest.counts.inactive_workflows !== inactive.workflows.length || manifest.counts.active_workflows + manifest.counts.inactive_workflows !== 1500) errors.push('final catalogue counts do not reconcile')
if (interactiveManifest.counts.workflows !== interactiveCatalog.workflows.length || interactiveCatalog.workflows.length !== manifest.counts.active_workflows) errors.push('interactive catalogue counts do not reconcile')
const result = { status: errors.length ? 'FAIL' : 'PASS', baseline_distinct_inactive: baseline.baseline_distinct_inactive_count, families: families.family_count, targets: targets.target_count, activated: activation.activated_count, source_registry: registry.ending_registry_count, active_workflows: manifest.counts.active_workflows, inactive_workflows: manifest.counts.inactive_workflows, errors }; console.log(JSON.stringify(result, null, 2)); if (errors.length) process.exitCode = 1
