import fs from 'node:fs'
import path from 'node:path'
const root = process.cwd(); const progress = path.join(root, 'clinical-expansion-v2/progress/family-wave6'); const beta = path.join(root, 'public/data-beta'); const read = file => JSON.parse(fs.readFileSync(file, 'utf8')); const errors = []
const baseline = read(path.join(progress, 'DISTINCT_INACTIVE_BASELINE_WAVE6.json')); const families = read(path.join(progress, 'FAMILY_TARGETS_WAVE6.json')); const targets = read(path.join(progress, 'WAVE6_WORKFLOW_TARGETS.json')); const reuse = read(path.join(progress, 'EXISTING_SOURCE_REUSE_WAVE6.json')); const gaps = read(path.join(progress, 'NAMED_EVIDENCE_GAPS_WAVE6.json')); const packs = read(path.join(progress, 'WORKFLOW_EVIDENCE_PACKS_WAVE6.json')); const matrix = read(path.join(progress, 'WORKFLOW_COMPLETENESS_MATRIX_WAVE6.json')); const diff = read(path.join(progress, 'SCHEMA_DIFFERENTIATION_MATRIX_WAVE6.json')); const activation = read(path.join(progress, 'WORKFLOW_ACTIVATION_RESULTS_WAVE6.json')); const provenance = read(path.join(progress, 'FIELD_PROVENANCE_WAVE6.json')); const audit = read(path.join(progress, 'WAVE5_ACTIVATION_DISTINCTNESS_AUDIT.json')); const adversarial = read(path.join(progress, 'WAVE5_ADVERSARIAL_RESULTS.json')); const manifest = read(path.join(beta, 'final-catalogue/manifest.json')); const catalog = read(path.join(beta, 'final-catalogue/catalog.json')); const inactive = read(path.join(beta, 'final-catalogue/inactive-inventory.json'))
if (baseline.baseline_inactive_count !== 969 || baseline.records.length !== 969) errors.push('inactive baseline does not equal 969')
if (families.family_count !== 15 || families.families.length !== 15) errors.push('family count does not equal 15')
if (targets.target_count < 90 || targets.target_count > 120 || targets.targets.length !== targets.target_count) errors.push('target count is outside 90-120')
if (new Set(targets.targets.map(target => target.workflow_id)).size !== targets.target_count) errors.push('duplicate target IDs')
if (activation.target_count !== targets.target_count || activation.activated_count !== 90 || activation.results.length !== targets.target_count) errors.push('activation totals do not reconcile')
if (packs.workflow_count !== targets.target_count || matrix.workflow_count !== targets.target_count || diff.workflow_count !== targets.target_count) errors.push('workflow artifact totals do not reconcile')
if (audit.activated_workflow_count !== 74 || audit.clone_groups.length !== 0) errors.push('Wave-5 distinctness audit has unresolved clone groups')
if (adversarial.fixture_count !== 20 || adversarial.passed !== 20 || adversarial.status !== 'PASS') errors.push('Wave-5 adversarial proof incomplete')
if (reuse.source_registry_count !== 242) errors.push('source reuse registry count drifted')
if (gaps.unresolved_count !== gaps.gaps.length || gaps.gaps.some(gap => !gap.required_section || !gap.target_workflow_ids?.length || !gap.expected_authoritative_organisation)) errors.push('named gap records incomplete')
if (manifest.counts.original_workflows !== 1500 || manifest.counts.active_workflows !== 621 || manifest.counts.inactive_workflows !== 879) errors.push('catalogue counts do not match Wave-6 result')
if (catalog.workflows.length !== 621 || inactive.workflows.length !== 879) errors.push('active/inactive catalogue counts do not match')
for (const target of targets.targets) { const result = activation.results.find(row => row.workflow_id === target.workflow_id); if (!result) errors.push(`${target.workflow_id}: missing terminal state`); if (!['activated_with_complete_authoritative_evidence','remains_inactive_missing_named_critical_evidence','remains_inactive_wrong_population','remains_inactive_wrong_setting','remains_inactive_scope_not_distinct','incorporated_into_existing_active_workflow','retired_duplicate_with_redirect','blocked_by_source_access','blocked_by_technical_error'].includes(result?.final_state)) errors.push(`${target.workflow_id}: invalid terminal state`); if (result?.final_state === 'activated_with_complete_authoritative_evidence' && !fs.existsSync(path.join(beta, 'interactive-workflows/workflows', `${target.workflow_id}.json`))) errors.push(`${target.workflow_id}: activated detail missing`) }
if (provenance.fields.some(field => !field.workflow_id || !field.field_id || !field.evidence_pack_ids?.length || !field.source_ids?.length || !field.exact_section || !field.population_qualifier || !field.setting_qualifier)) errors.push('field provenance incomplete')
console.log(JSON.stringify({ status: errors.length ? 'FAIL' : 'PASS', baseline: baseline.records.length, targetable_distinct: baseline.exact_targetable_distinct_inactive_total, families: families.family_count, targets: targets.target_count, activated: activation.activated_count, remaining_inactive: activation.remaining_inactive.length, active_workflows: manifest.counts.active_workflows, inactive_workflows: manifest.counts.inactive_workflows, fields_added: provenance.field_count, wave5_adversarial: `${adversarial.passed}/${adversarial.fixture_count}`, errors }, null, 2)); if (errors.length) process.exitCode = 1
